### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by hoppus** [freshdesk/freshchat-ios#1]
Add please Carthage support

**Comment by harish-kumarc** [comment]
Hi @hoppus 
Yes we will do support for Carthage in future but not now, Currently we are working on lined-up enhancements and fixed for available SDK.

Thanks

**Comment by dcondrau** [comment]
Carthage is not supported yet, correct?

**Comment by tryprasannan** [comment]
@dcondrau Yes, we don't support this yet.

**Comment by dcondrau** [comment]
@tryprasannan Thanks for the replly. Do you have any tips how to add the library manually to Xcode project? Not even sure if that is possible? We are on Swift+Carthage and won't add Cocoapods to the mixl.
I did the following without success:
- added libFDFreshchatSDK.h to "Linked Frameworks and Libraries"
- added FreshchatSDK.h to "Framework Search Paths"
- added #import "FreshchatSDK.h" to Objc-Bridging-Header File

import FreshchatSDK still errors for me with "No such module"

**Comment by harish-kumarc** [comment]
Correct @dcondrau officially not yet. But you can build it via creating dynamic framework with Freshchat SDK and add to separate branch for use. We will surely keep you updated about Carthage support.

**Comment by gabors** [comment]
Can you guys please provide instructions how to add the libFDFreshchatSDK.a to a pure swift project.
I've added it as I would normally add a static library with a bridging headers, similar to what @dcondrau described.  In my case I do not see the No such module error, but I do get 22 build errors:

`Undefined symbols for architecture x86_64:
  "_NSSQLiteStoreType", referenced from:
      -[KonotorDataManager linkPSC:URL:mode:errorInfo:] in libFDFreshchatSDK.a(KonotorDataManager.o)
      -[KonotorDataManager isMigrationRequired:storeURL:] in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_NSSQLitePragmasOption", referenced from:
      -[KonotorDataManager configWithJournalDisabled] in libFDFreshchatSDK.a(KonotorDataManager.o)
      -[KonotorDataManager configWithJournalWALMode] in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_OBJC_CLASS_$_PHPhotoLibrary", referenced from:
      objc-class-ref in libFDFreshchatSDK.a(KonotorImageInput.o)
  "_NSMergeByPropertyObjectTrumpMergePolicy", referenced from:
      -[KonotorDataManager prepareMainContext] in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_OBJC_CLASS_$_NSFetchRequest", referenced from:
      objc-class-ref in libFDFreshchatSDK.a(KonotorCustomProperty.o)
      objc-class-ref in libFDFreshchatSDK.a(HLArticle.o)
      objc-class-ref in libFDFreshchatSDK.a(HLMessageServices.o)
      objc-class-ref in libFDFreshchatSDK.a(HLCsat.o)
      objc-class-ref in libFDFreshchatSDK.a(FDParticipant.o)
      objc-class-ref in libFDFreshchatSDK.a(HLCoreServices.o)
      objc-class-ref in libFDFreshchatSDK.a(FDIndexManager.o)
      ...
  "_OBJC_CLASS_$_NSManagedObjectModel", referenced from:
      objc-class-ref in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_OBJC_CLASS_$_NSEntityDescription", referenced from:
      objc-class-ref in libFDFreshchatSDK.a(KonotorAudioRecorder.o)
      objc-class-ref in libFDFreshchatSDK.a(KonotorCustomProperty.o)
      objc-class-ref in libFDFreshchatSDK.a(HLArticle.o)
      objc-class-ref in libFDFreshchatSDK.a(HLCsat.o)
      objc-class-ref in libFDFreshchatSDK.a(FDParticipant.o)
      objc-class-ref in libFDFreshchatSDK.a(FDIndexManager.o)
      objc-class-ref in libFDFreshchatSDK.a(KonotorConversation.o)
      ...
  "_AudioSessionSetActiveWithFlags", referenced from:
      +[KonotorAudioRecorder UnInitRecorder] in libFDFreshchatSDK.a(KonotorAudioRecorder.o)
      +[KonotorAudioPlayer UnInitPlayer] in libFDFreshchatSDK.a(KonotorAudioPlayer.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[FDReachability startNotifier] in libFDFreshchatSDK.a(FDReachability.o)
      -[FDReachability stopNotifier] in libFDFreshchatSDK.a(FDReachability.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      -[FDReachability isReachable] in libFDFreshchatSDK.a(FDReachability.o)
      -[FDReachability isReachableViaWiFi] in libFDFreshchatSDK.a(FDReachability.o)
      -[FDReachability connectionRequired] in libFDFreshchatSDK.a(FDReachability.o)
      -[FDReachability isConnectionOnDemand] in libFDFreshchatSDK.a(FDReachability.o)
      -[FDReachability isInterventionRequired] in libFDFreshchatSDK.a(FDReachability.o)
      -[FDReachability reachabilityFlags] in libFDFreshchatSDK.a(FDReachability.o)
  "_OBJC_CLASS_$_NSPersistentStoreCoordinator", referenced from:
      objc-class-ref in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_NSMigratePersistentStoresAutomaticallyOption", referenced from:
      -[KonotorDataManager configWithJournalDisabled] in libFDFreshchatSDK.a(KonotorDataManager.o)
      -[KonotorDataManager configWithJournalWALMode] in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_AudioSessionSetProperty", referenced from:
      +[KonotorAudioPlayer PlayMessage:atTime:] in libFDFreshchatSDK.a(KonotorAudioPlayer.o)
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      +[FDReachability reachabilityWithAddress:] in libFDFreshchatSDK.a(FDReachability.o)
  "_OBJC_CLASS_$_NSManagedObject", referenced from:
      _OBJC_CLASS_$_KonotorCustomProperty in libFDFreshchatSDK.a(KonotorCustomProperty.o)
      _OBJC_CLASS_$_HLArticle in libFDFreshchatSDK.a(HLArticle.o)
      _OBJC_CLASS_$_HLCsat in libFDFreshchatSDK.a(HLCsat.o)
      _OBJC_CLASS_$_FDParticipant in libFDFreshchatSDK.a(FDParticipant.o)
      _OBJC_CLASS_$_KonotorUser in libFDFreshchatSDK.a(KonotorUser.o)
      _OBJC_CLASS_$_KonotorConversation in libFDFreshchatSDK.a(KonotorConversation.o)
      _OBJC_CLASS_$_HLChannel in libFDFreshchatSDK.a(HLChannel.o)
      ...
  "_SCNetworkReachabilitySetDispatchQueue", referenced from:
      -[FDReachability startNotifier] in libFDFreshchatSDK.a(FDReachability.o)
      -[FDReachability stopNotifier] in libFDFreshchatSDK.a(FDReachability.o)
  "_OBJC_METACLASS_$_NSManagedObject", referenced from:
      _OBJC_METACLASS_$_KonotorCustomProperty in libFDFreshchatSDK.a(KonotorCustomProperty.o)
      _OBJC_METACLASS_$_HLArticle in libFDFreshchatSDK.a(HLArticle.o)
      _OBJC_METACLASS_$_HLCsat in libFDFreshchatSDK.a(HLCsat.o)
      _OBJC_METACLASS_$_FDParticipant in libFDFreshchatSDK.a(FDParticipant.o)
      _OBJC_METACLASS_$_KonotorUser in libFDFreshchatSDK.a(KonotorUser.o)
      _OBJC_METACLASS_$_KonotorConversation in libFDFreshchatSDK.a(KonotorConversation.o)
      _OBJC_METACLASS_$_HLChannel in libFDFreshchatSDK.a(HLChannel.o)
      ...
  "_OBJC_CLASS_$_NSManagedObjectContext", referenced from:
      objc-class-ref in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_CMTimeGetSeconds", referenced from:
      +[KonotorAudioRecorder SaveAudioMessageInCoreData:] in libFDFreshchatSDK.a(KonotorAudioRecorder.o)
      +[KonotorAudioRecorder SaveAudioMessageInCoreData:onConversation:] in libFDFreshchatSDK.a(KonotorAudioRecorder.o)
  "_NSInferMappingModelAutomaticallyOption", referenced from:
      -[KonotorDataManager configWithJournalDisabled] in libFDFreshchatSDK.a(KonotorDataManager.o)
      -[KonotorDataManager configWithJournalWALMode] in libFDFreshchatSDK.a(KonotorDataManager.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      +[FDReachability reachabilityWithHostname:] in libFDFreshchatSDK.a(FDReachability.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by harish-kumarc** [comment]
Hi @gabors , Can you please check if all req. frameworks for Freshchat are added. Here is the list **Foundation**, **AVFoundation**, **AudioToolbox**, **CoreMedia**, **CoreData**, **ImageIO**, **Photos**, **SystemConfiguration**, **Security**

**Comment by shruezee** [comment]
Hi
Im on XCode 8 and migrating project to 9.4.1 which is giving following error
"Module compiled with Swift 3.1 cannot be imported in Swift 3.3.2: ~projectModulePath/Alamofire.framework/Modules/Alamofire.swiftmodule/x86_64.swiftmodule" I have tried following to ressolve
1.  Rebuild all pod with carthage 
2. carthage update --platform iOS
even removed other versions of xcode to have one compiler version
still xcode is showing same error
Thanks in advance

**Comment by harish-kumarc** [comment]
Hi @shruezee , 
Can you check [here](https://stackoverflow.com/questions/44399109/xcode-9-module-compiled-with-swift-3-1-cannot-be-imported-in-swift-4-0) for similar issue while building. Also you can have a look initial version of Freshchat Carthage here- : https://github.com/freshdesk/freshchat-ios/tree/carthage. 

Thanks
Harish

**Comment by shruezee** [comment]
Many Thanks @harish-kumar for your quick response. 

Just double checked and confirming In SO link i have followed the steps 1. sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer and 2. Update with No use binaries still i had same issue. 

This project just using Almofire and Swifty-JSON and not using Chat for using the freshchat-ios.

Please let me know if you need more information

Best Regards
Shruthi

**Comment by harish-kumarc** [comment]
Hi @shruezee , 

Can you please try following steps for your project :
1. Please try cleaning the project cmd + shift + k and build folder cmd + option + shift + k and deleting the derived data folder.
2. Go to Build Settings > Swift Language Version for all of your Targets.

Please try and let us know if the issue is fixed.

Thanks

**Comment by shruezee** [comment]
Greetings @Harish

I have tried clearing the derived data folder from preference > locations also tried Shift+cmd+Alt to clean build folder still have same issue.
Please note this project built in Xcode 8 on Swift 3 and I am trying to migrate to 4 or 5. 

In Build setting I see Swift 3.3 and Swift 4.1 as language option in Xcode 9.4.1. 
Moreover, Also tried downloading Xcode 9.1 and cleared multiple versions of xcode to resolve this error. 
Still have <unknown>:0 error: module compiled with swift 3.1 cannot be imported in swift 4.1.2: ~ProjectPath/Alamofire.framework/Modules/Alamofire.swiftmodule/x86_64.swiftmodule

Feel free to reach me if you have faced similar issue or know how to resolve this.

Many Thanks
Shruthi

**Comment by shruezee** [comment]
Greetings @Harish

I have tried clearing the derived data folder from preference > locations also tried Shift+cmd+Alt to clean build folder still have same issue.
Please note this project built in Xcode 8 on Swift 3 and I am trying to migrate to 4 or 5. 

In Build setting I see Swift 3.3 and Swift 4.1 as language option in Xcode 9.4.1. 
Moreover, Also tried downloading Xcode 9.1 and cleared multiple versions of xcode to resolve this error. 
Still have <unknown>:0 error: module compiled with swift 3.1 cannot be imported in swift 4.1.2: ~ProjectPath/Alamofire.framework/Modules/Alamofire.swiftmodule/x86_64.swiftmodule

Feel free to reach me if you have faced similar issue or know how to resolve this.

Many Thanks
Shruthi

**Comment by harish-kumar** [comment]
Guys,

I have no idea why I'm getting these emails or how you got my email
address. But I think I'm included in this conversation by mistake.

**Comment by havard024** [comment]
+1
