### ISSUE TITLE
Can not change icon in Freshchat

### ISSUE THREAD

**Issue by Linkadi98** [freshdesk/freshchat-ios#101]
Hello, 
Our company's project uses Freshchat on iOS like a Message tool to help customers contact with us, but as usual, we have to custom the Freshchat UI, therefore we need to replace icons in Freshchat, but we can't not change the default icons in Freshchat UI, I don't see any guide in the Freshchat's custom theme guide that help us to change the icon in the Freshchat's UI. I made a bundle just like the FCResources.bundle and use the resources in our bundle but not help us so much. How can we do this? 
Thank you!

**Comment by harish-kumarc** [comment]
Hi @Linkadi98 
All the UI elements are customisable in Freshchat with icons. We provide a FCTheme.plist file that contains all the icons names with path under FCResources.bundle. You can change either icon path there or replace respective icon under Images folder. Icons names are also quite informative.
For UI elements we have a theme customisation guide, please check doc link [here](https://support.freshchat.com/support/solutions/articles/229814-freshchat-ios-sdk-themes)

**Comment by Linkadi98** [comment]
Hello, 
We did solve this problem because some mistakes when setting the bundle.
