### ISSUE TITLE
Apple push notification (APN)

### ISSUE THREAD

**Issue by Bran-nod** [freshdesk/freshchat-ios#103]
ios 13.3.1 / 12
SDK v3.6.0

Don't receive push notifications now, but in earlier versions we do.

**Comment by hemanth-sudarsan** [comment]
@Bran-nod 
Please make sure you see the Push Notification enabled is coming as YES inside the User properties section under user details. If not that means we have not received device token.
<img width="292" alt="Screenshot 2020-05-23 at 6 20 41 PM" src="https://user-images.githubusercontent.com/45059530/82732300-ffdb3f00-9d29-11ea-8a51-4c776e555936.png">

Under Capabilities add Background mode and check remote notifications, sometimes it seems a problem.

**Comment by hemanth-sudarsan** [comment]
@Bran-nod Please feel free to open, if the problem persists.
