### ISSUE TITLE
SDK v3.6.1+ fails to build on Xcode 11.3.1

### ISSUE THREAD

**Issue by ealeksandrov** [freshdesk/freshchat-ios#106]
On CI machine (Xcode 11.3.1 + macOS 11.14) starting with version 3.6.1 of Freshchat SDK I receive this error:
```
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1103.0.32.59.0_0' Reader: '1100.0.33.17_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.17)' for architecture arm64
```

On local Xcode 11.5 everything is fine. But I don't plan to update Xcode on CI system anytime soon since Xcode 11.4+ requires macOS Catalina 10.15.2 or later.

This is a breaking compatibility change, so please add it to release notes.

**Comment by hemanth-sudarsan** [comment]
@ealeksandrov The latest version we have made SDK to build from Xcode 11.
In future we will mention it in Release notes.
