### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException *** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: 8) -[FCMessageController handleUserEvadedCSAT] keyboard_arrow_down

### ISSUE THREAD

**Issue by mfmansueli** [freshdesk/freshchat-ios#108]
FreshChat SDK 3.7.1

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1dfe8a3a8 __exceptionPreprocess
1  libobjc.A.dylib                0x1df08fd00 objc_exception_throw
2  CoreFoundation                 0x1dfe01870 _CFArgv
3  CoreFoundation                 0x1dfd73714 -[__NSDictionaryM setObject:forKey:]
4  Shipp Cliente                  0x10313be04 -[FCMessageController handleUserEvadedCSAT]
5  Shipp Cliente                  0x103131a4c -[FCMessageController viewWillDisappear:]
6  UIKitCore                      0x20cb91400 -[UIViewController _setViewAppearState:isAnimating:]
7  UIKitCore                      0x20cb917a8 __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke
8  CoreFoundation                 0x1dfd6dd24 -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:]
9  UIKitCore                      0x20cb91550 -[UIViewController _setViewAppearState:isAnimating:]
10 UIKitCore                      0x20cb91b28 -[UIViewController __viewWillDisappear:]
11 UIKitCore                      0x20caf8d00 -[UINavigationController _startTransition:fromViewController:toViewController:]
12 UIKitCore                      0x20caf99bc -[UINavigationController _startDeferredTransitionIfNeeded:]
13 UIKitCore                      0x20cafac94 -[UINavigationController __viewWillLayoutSubviews]
14 UIKitCore                      0x20cadd374 -[UILayoutContainerView layoutSubviews]
15 UIKitCore                      0x20d611e00 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
16 libobjc.A.dylib                0x1df08b454 -[NSObject performSelector:withObject:]
17 QuartzCore                     0x1e43dab08 -[CALayer layoutSublayers]
18 QuartzCore                     0x1e43dadf4 CA::Layer::layout_if_needed(CA::Transaction*)
19 QuartzCore                     0x1e4342050 CA::Context::commit_transaction(CA::Transaction*)
20 QuartzCore                     0x1e4370f1c CA::Transaction::commit()
21 QuartzCore                     0x1e4371cb0 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
22 CoreFoundation                 0x1dfe199d8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
23 CoreFoundation                 0x1dfe144d0 __CFRunLoopDoObservers
24 CoreFoundation                 0x1dfe14a30 __CFRunLoopRun
25 CoreFoundation                 0x1dfe14254 CFRunLoopRunSpecific
26 GraphicsServices               0x1e2053d8c GSEventRunModal
27 UIKitCore                      0x20d15c4c0 UIApplicationMain
28 Shipp Cliente                  0x102e196f8 main + 25 (UpdateAppViewController.swift:25)
29 libdyld.dylib                  0x1df8d0fd8 start

**Comment by harish-kumarc** [comment]
Thanks for the logs @mfmansueli, we will analyse and update you. Do you have any steps to replicate the crash?

**Comment by harish-kumarc** [comment]
We have the crash with release [v3.7.4](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.7.4). Please update to latest SDK.
