### ISSUE TITLE
Crash -[FCMessageController willMoveToParentViewController:]

### ISSUE THREAD

**Issue by mfmansueli** [freshdesk/freshchat-ios#109]
FreshChat SDK 3.7.1

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x193405c68 (Ausente)
1  libobjc.A.dylib                0x19311d79c (Ausente)
2  CoreFoundation                 0x193472aac (Ausente)
3  CoreFoundation                 0x19347e48c (Ausente)
4  CoreFoundation                 0x1932eb2a8 (Ausente)
5  Shipp Cliente                  0x1008cf530 -[FCMessageController willMoveToParentViewController:]
6  UIKitCore                      0x197442b5c (Ausente)
7  Shipp Cliente                  0x100898098 -[FCContainerController viewDidLoad]
8  UIKitCore                      0x19743a078 (Ausente)
9  UIKitCore                      0x19743e720 (Ausente)
10 UIKitCore                      0x19743eae4 (Ausente)
11 UIKitCore                      0x197394af4 (Ausente)
12 UIKitCore                      0x197336418 (Ausente)
13 UIKitCore                      0x1973324bc (Ausente)
14 UIKitCore                      0x197fc1e5c (Ausente)
15 UIKitCore                      0x197b18f7c (Ausente)
16 UIKitCore                      0x197b086c0 (Ausente)
17 UIKitCore                      0x197b3a218 (Ausente)
18 CoreFoundation                 0x1933821d0 (Ausente)
19 CoreFoundation                 0x19337c94c (Ausente)
20 CoreFoundation                 0x19337ce60 (Ausente)
21 CoreFoundation                 0x19337c630 (Ausente)
22 GraphicsServices               0x19f156818 (Ausente)
23 UIKitCore                      0x197b09a38 (Ausente)
24 UIKitCore                      0x197b0f928 (Ausente)
25 Shipp Cliente                  0x1005b96f8 main + 25 (UpdateAppViewController.swift:25)
26 libdyld.dylib                  0x19320838c (Ausente)

**Comment by harish-kumarc** [comment]
Thanks for the logs. We have made improvements with SDK v3.7.2, can you update and let us know if the crash still happens.
