### ISSUE TITLE
API or webhook to fetch all chats per user

### ISSUE THREAD

**Issue by eshwartm** [freshdesk/freshchat-ios#11]
Is there a API or webhook or something we can fetch all the chats in our freshchat integration ?

**Comment by tryprasannan** [comment]
@eshwartm Can you please expand on what you're trying to achieve ? 

This repo contains SDK to include in your app for your users to reach out to you/the business and the business can respond from Freshchat Web Portal or Mobile apps on Android & iOS.

**Comment by sairasamdanii** [comment]
@tryprasannan But then how will a user fetch his chat history?

**Comment by harish-kumarc** [comment]
Please refer to our API documentation linked [here](https://developers.freshchat.com/api/)
