### ISSUE TITLE
Crash -__60-[FCDataManager deleteAllEntriesOfEntity:handler:inContext:]_block_invoke

### ISSUE THREAD

**Issue by mfmansueli** [freshdesk/freshchat-ios#110]
FreshChat SDK 3.7.1

Crashed: com.apple.main-thread
0  CoreData                       0x1a3235510 -[NSManagedObjectContext _thereIsNoSadnessLikeTheDeathOfOptimism].cold.1 + 28
1  CoreData                       0x1a30b00b0 -[NSManagedObjectContext _youcreatedanNSManagedObjectContextOnthemainthreadandillegallypassedittoabackgroundthread] + 14
2  CoreData                       0x1a2f792c4 -[NSManagedObjectContext save:] + 2168
3  Shipp Cliente                  0x10073ee7c __60-[FCDataManager deleteAllEntriesOfEntity:handler:inContext:]_block_invoke + 4380012156
4  CoreData                       0x1a30b34cc developerSubmittedBlockToNSManagedObjectContextPerform + 164
5  libdispatch.dylib              0x19e24033c _dispatch_client_callout + 20
6  libdispatch.dylib              0x19e24c600 _dispatch_main_queue_callback_4CF + 832
7  CoreFoundation                 0x19e51b6b0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8  CoreFoundation                 0x19e5162c8 __CFRunLoopRun + 1708
9  CoreFoundation                 0x19e5158f4 CFRunLoopRunSpecific + 480
10 GraphicsServices               0x1a892c604 GSEventRunModal + 164
11 UIKitCore                      0x1a26e9358 UIApplicationMain + 1944
12 Shipp Cliente                  0x1004016f8 main + 25 (UpdateAppViewController.swift:25)
13 libdyld.dylib                  0x19e3912dc start + 4

Device info:
Model: iPhone 11 Pro
Orientation: Portrait
Free space in RAM: 97.16 MB
Free disk space: 189.16 GB
plat_ios Operating system
Version: 13.5.1 (17F80)
Orientation: Portrait
Unlocked: No

**Comment by harish-kumarc** [comment]
Thanks for the logs @mfmansueli, we will analyse and update you on this.

**Comment by harish-kumarc** [comment]
@mfmansueli We have fixed it with release [v3.7.4](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.7.4). Please update to latest SDK.
