### ISSUE TITLE
Crash -[FCDataManager save]

### ISSUE THREAD

**Issue by mfmansueli** [freshdesk/freshchat-ios#111]
FreshChat SDK 3.7.1

Crashed: com.apple.main-thread
0  CoreData                       0x18d6c1510 -[NSManagedObjectContext _thereIsNoSadnessLikeTheDeathOfOptimism].cold.1 + 28
1  CoreData                       0x18d53c0b0 -[NSManagedObjectContext _youcreatedanNSManagedObjectContextOnthemainthreadandillegallypassedittoabackgroundthread] + 14
2  CoreData                       0x18d4052c4 -[NSManagedObjectContext save:] + 2168
3  Shipp Cliente                  0x1028e9b44 -[FCDataManager save] + 4375829316
4  Shipp Cliente                  0x1028e5018 +[FCMessageFragments createFragments:toMessage:] + 4375810072
5  Shipp Cliente                  0x1028fe4f4 +[FCMessages createNewMessage:toChannelID:] + 4375913716
6  Shipp Cliente                  0x102883a14 +[FCChannels updateChannel:withInfo:] + 4375411220
7  Shipp Cliente                  0x1028386e4 __44+[FCMessageServices importChannels:handler:]_block_invoke + 4375103204
8  CoreData                       0x18d53f4cc developerSubmittedBlockToNSManagedObjectContextPerform + 164
9  libdispatch.dylib              0x1886cc33c _dispatch_client_callout + 20
10 libdispatch.dylib              0x1886d8600 _dispatch_main_queue_callback_4CF + 832
11 CoreFoundation                 0x1889a76b0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
12 CoreFoundation                 0x1889a22c8 __CFRunLoopRun + 1708
13 CoreFoundation                 0x1889a18f4 CFRunLoopRunSpecific + 480
14 GraphicsServices               0x192db8604 GSEventRunModal + 164
15 UIKitCore                      0x18cb75358 UIApplicationMain + 1944
16 Shipp Cliente                  0x1025ad6f8 main + 25 (UpdateAppViewController.swift:25)
17 libdyld.dylib                  0x18881d2dc start + 4

Device
Model: iPhone XS
Orientation: Portrait
Free space in RAM: 76.58 MB
Free disk space: 213.76 GB
plat_ios Operating system
Version: 13.5.1 (17F80)
Orientation: Portrait
Unlocked: No

**Comment by harish-kumarc** [comment]
@mfmansueli We have made changes with release [v3.7.4](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.7.4). Please update to latest SDK and let us know if the issue resurface again.
