### ISSUE TITLE
Application Crashing

### ISSUE THREAD

**Issue by vlamoly** [freshdesk/freshchat-ios#112]
Hello, 
Our iOS application is not working anymore because while starting we have 
It was working 3 hour ago. Please help, all of our customers is blocked. 

`
[INFO]  CoreData: annotation:  Failed to load optimized model at path '/Users/LasticLaptop/Library/Developer/CoreSimulator/Devices/647D7AF9-2888-4BF8-8844-582C88EF2EBD/data/Containers/Bundle/Application/82D777C2-D605-4263-A51A-338C76E1D4C3/PsyTools.app/FreshchatModels.bundle/FreshchatModel.momd/FreshchatModel 3.omo'

[INFO]  -[NSNull count]: unrecognized selector sent to instance 0x114080ff0
[INFO]  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance 0x114080ff0'
[INFO]  *** First throw call stack:
[INFO]  (
[INFO]          0   CoreFoundation                      0x0000000113df727e __exceptionPreprocess + 350
[INFO]          1   libobjc.A.dylib                     0x000000011322eb20 objc_exception_throw + 48
[INFO]          2   CoreFoundation                      0x0000000113e17fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
[INFO]          3   CoreFoundation                      0x0000000113dfbc4c ___forwarding___ + 1436
[INFO]          4   CoreFoundation                      0x0000000113dfdf78 _CF_forwarding_prep_0 + 120
[INFO]          5   PsyTools                            0x000000010c9e7107 +[FBSDKRestrictiveDataFilterManager updateFilters:] + 62
[INFO]          6   PsyTools                            0x000000010c9e0172 +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 1944
[INFO]          7   PsyTools                            0x000000010c9df9a9 __78+[FBSDKServerConfigurationManager loadServerConfigurationWithCompletionBlock:]_block_invoke + 62
[INFO]          8   PsyTools                            0x000000010ca1c719 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 146
[INFO]          9   PsyTools                            0x000000010ca26dc3 __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 145
[INFO]          10  PsyTools                            0x000000010ca26ccf -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 638
[INFO]          11  PsyTools                            0x000000010ca268a0 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 449
[INFO]          12  CoreFoundation                      0x0000000113dc51e7 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
[INFO]          13  CoreFoundation                      0x0000000113d0a7d4 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 228
[INFO]          14  PsyTools                            0x000000010ca26606 -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 658
[INFO]          15  PsyTools                            0x000000010ca256d2 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 754
[INFO]          16  PsyTools                            0x000000010ca23717 __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 72
[INFO]          17  libdispatch.dylib                   0x0000000116134848 _dispatch_call_block_and_release + 12
[INFO]          18  libdispatch.dylib                   0x00000001161357b9 _dispatch_client_callout + 8
[INFO]          19  libdispatch.dylib                   0x0000000116141c9b _dispatch_main_queue_callback_4CF + 1212
[INFO]          20  CoreFoundation                      0x0000000113d5a049 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
[INFO]          21  CoreFoundation                      0x0000000113d54ca9 __CFRunLoopRun + 2329
[INFO]          22  CoreFoundation                      0x0000000113d54066 CFRunLoopRunSpecific + 438
[INFO]          23  GraphicsServices                    0x0000000119777bb0 GSEventRunModal + 65
[INFO]          24  UIKitCore                           0x000000011e662d4d UIApplicationMain + 1621
[INFO]          25  PsyTools                            0x000000010c7e145c main + 1212
[INFO]          26  libdyld.dylib                       0x00000001161b6c25 start + 1
[INFO]          27  ???                                 0x0000000000000001 0x0 + 1
[INFO]  )
[INFO]  libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by harish-kumarc** [comment]
Hi @vlamoly, Can you please try clearing the project and then delete derived data.

**Comment by harish-kumarc** [comment]
@vlamoly, Hope your query is resolved, Feel free to open if it comes again. Thanks
