### ISSUE TITLE
notificationBanner in app overlays status bar

### ISSUE THREAD

**Issue by Ganyev** [freshdesk/freshchat-ios#114]
Hello there,
When we get a message, it is shown in notificationBanner. And on devices like iPhone 6,7,8 this banner overlays status bar and it looks not pretty. 
<img width="357" alt="Снимок экрана 2020-07-17 в 13 08 18" src="https://user-images.githubusercontent.com/41617899/87758629-9f9ae200-c82e-11ea-9965-878daf9842e9.png">

Can you, please, make this banner's frame higher or something to fix this issue?

For X devices with "safe areas" it looks OK
<img width="294" alt="Снимок экрана 2020-07-17 в 13 02 29" src="https://user-images.githubusercontent.com/41617899/87758189-ce648880-c82d-11ea-8692-9ec5115e24fd.png">

**Comment by harish-kumarc** [comment]
Hi @Ganyev , which version of SDK are you using inside your application? The issues was there with old versions and fixed with release v3.3.0.

**Comment by Ganyev** [comment]
@harish-kumarc hi, we facing this issue on version 3.3.0

**Comment by harish-kumarc** [comment]
@Ganyev With release v3.3.3 (https://github.com/freshdesk/freshchat-ios/releases/tag/v3.3.3) its fixed and mentioned under bug fixes in release notes. Apologies as previously mentioned v3.3.0 instead of v3.3.3.

**Comment by Ganyev** [comment]
Thanks!
