### ISSUE TITLE
Cannot attach files

### ISSUE THREAD

**Issue by gavin928** [freshdesk/freshchat-ios#116]
Hello~
I got an issue about attaching the files. I have integrated the sdk of version 3.7.4 successfully which is tested to have conversation between console and the app. However, when I tried to click the attach icon on the bottom left corner, the button is highlighted and keyboard released but no gallery was shown. Could anybody please help about this issue? I have already set the NSPhotoLibraryUsageDescription is plist. Thanks a lots.

**Comment by harish-kumarc** [comment]
Thanks for the information, We have tried and failed to replicate the issue. Can you please let us know the following:
1. Which version of XCode are you using to build the project 
2. iOS version with device name.
Thanks

**Comment by gavin928** [comment]
1. Xcode 11.2.1
2. iPhone 11 - 13.2.2 & iPhone SE - 10.3.1

**Comment by harish-kumarc** [comment]
Hi @gavin928 we tried with similar device configuration but failed to replicate the issue. Can you share a sample app with us so we can analyse if anything missed.

**Comment by harish-kumarc** [comment]
Hi @gavin928, We are closing the issue as you have mentioned in conversation with our support team that `your project's method swizzling is blocking attachment option alert controller to present`.
