### ISSUE TITLE
Loading indefinitely Sometimes & No Push notifications

### ISSUE THREAD

**Issue by ajinkyashelar** [freshdesk/freshchat-ios#12]
Hi,

It woule be great if you can help me resolve some of my issues. 

I have integrated the FreshChat iOS SDK 1.3.2 in one of my iOS apps. 

1. Sometimes or mostly on the first time launch of the app when the fresh chat is invoked using below method the conversation screen is presented but it gets stuck on loading screen for an indefinite time.  
`Freshchat.sharedInstance().showConversations(self)`

![simulator screen shot - iphone x - 2018-05-09 at 23 24 20](https://user-images.githubusercontent.com/1098658/39831033-d48fc684-53e0-11e8-96bc-62735def742b.png)

2. I have uploaded the production push notifications certificate but the push notifications are not received on the production environment device. 

3. The messages received on the iOS Chat conversation screen are delayed by almost 10-20 seconds while on Android they are more instantaneous.

Let me know if you need any more inputs. Thanks in advance.

**Comment by harish-kumarc** [comment]
Hi @ajinkyashelar 
Here's the resolution for your queries/issues with Freshchat integration -
1. Delay in first time channels/conversation loading : First time after Freshchat init, conversations API fetch all your channels list and and in recursive loads it usually update. Usually delay in loading happens due to factors like rough network/ erroneous implementation. It would be great if you can share your implementation snippets with us, we can help you better.

 2. Push notification error :  Can you please cross check if you are uploading correct envt. certificate (dev certificate or production). For production cert please make sure “Production Certificate” check box is applied. And if you are testing with both development and production push with same account then there will be a delay of half an hour in push after uploading cert for development to production or vice-versa.

3. Message delay : Yes we  have a casual delay of few secs, but once Freshchat’s push is aligned correctly with your app, then there won’t be any delay in receiving messages.

Thanks

**Comment by ajinkyashelar** [comment]
Hi @harish-kumarc 

Thanks for your response,
1. I have confirmed this and the issue persist only when fresh chat is initiated on the first launch of the app. No solution on it yet. 
2. Done. We were able to get this resolved by uploading a fresh Production certificate after multiple attempts. 
3. You were right now this is working well.

**Comment by harish-kumarc** [comment]
Great! @ajinkyashelar your issue no. 2. and 3. are resolved. 
For issue 1. - We cross checked and are'nt able to replicate infinite loading in conversation screen issue on our side.

Can you give us more context and please provide us the following infos from your side to debug it
- Are you initialising SDK in AppDelegate or doing it in same method/function where you are calling show conv. api. (need your code snippet for same).
- Are you testing in wifi or LTE mode.
- Can you try it in different device. Also need you device specs(iOS version/ model)

Please check our sample app and let us know if issue persists there.
Also, Can you update to Latest SDK version v1.3.3 for your app.

Thanks

**Comment by agusso** [comment]
Hi @harish-kumarc , I experience exactly the same problem as @ajinkyashelar on issue 1 where at the first time launch of the app when the fresh chat is invoked, it gets stuck on loading screen for an indefinite time. It only happen at the first launch when the same app is not installed in the device. 

#### Method called:
Freshchat.sharedInstance().showConversations(self)

#### SDK used:
version 1.4.2

#### Recreation steps:
- Delete the app from the device
- Install the same app
- Invoke Freshchat conversation

Kindly advise.

**Comment by harish-kumarc** [comment]
HI @agusso , 
The common reasons for infinite loading are invalid Freshchat's appId/appKey or init itself not getting called. Can you please add breakpoints and check if init is getting called(in first launch) and also check for valid appId/appKey are available with init method. 
We failed to replicate the issue using the steps you mentioned above.
We recommend you to check same with Freshchat's sample app (add your appId and appKey in AppDelegate file) and let us know if the issue is still there. You can download sample from [here](https://github.com/freshdesk/freshchat-ios/tree/master/Sample).

Thanks

**Comment by agusso** [comment]
Hi @harish-kumarc,

`The init is called in first launch and it is put in didFinishLaunchingWithOptions

        let freschatConfig: FreshchatConfig = FreshchatConfig.init(appID: chatAppId, andAppKey: chatAppKey)
        
        // Theme
        freschatConfig.themeName = "ChatTheme"
        
        // Features config
        freschatConfig.gallerySelectionEnabled = true
        freschatConfig.cameraCaptureEnabled = false
        freschatConfig.teamMemberInfoVisible = true
        freschatConfig.showNotificationBanner = true
        
        Freshchat.sharedInstance().initWith(freschatConfig)
`
appkey and appId are called correctly.

And the problem still persists.

**Comment by harish-kumarc** [comment]
@agusso 
I am not sure if the exact values are passed for "chatAppId" and "chatAppKey", into your init code. I am attaching here a sample project with same code that you have added above. Please check and update us about it (:
Also need a basic confirmation from your side that the you have activated Freshchat's account after receiving the welcome email.

Thanks
[SwiftSample.zip](https://github.com/freshdesk/freshchat-ios/files/2125040/SwiftSample.zip)

**Comment by agusso** [comment]
@harish-kumarc 
Apparently in my case the Freshchat init is called before clearing the keychain.
Whenever the keychain is cleared, it needs to initialise the Freshchat again.

**Comment by harish-kumarc** [comment]
@agusso 
Yes, we store some info's in secure store/keychain and clearing will surely result into infinite loading as some keys are req. for initialisation and freshchat apis. Thanks for the information. Awesome you resolved the issue 👍 
Thanks

**Comment by raviLakhtariya** [comment]
hi i had setup freshchat in right way... as per your instruction guide..but still i cant get push notification in my app... i had also other notification get..but freshchat message i cant getit...if you had any demo where push is get then share me....and 

second issue i had checked is 

in didregisterremotenofication method i had set device token but after i print the token status...but status i get is  "token not set"...can you help me

**Comment by harish-kumarc** [comment]
Hi @raviLakhtariya , Seems like your token isn't generated properly, can you confirm that push is enabled for you application. 
After passing the token to Freshchat API the state for Push Enabled flag in portal is set to Yes(that way you confirm the token is passed correctly)
Attaching here sample apps with and without UNUserNotification. Please update your appId/Key and bundleId for samples and do let us know if you are able to fix it.
Thanks 

[FC_Push_Samples.zip](https://github.com/freshdesk/freshchat-ios/files/3236608/FC_Push_Samples.zip)

**Comment by raviLakhtariya** [comment]
Hi i had use your app and change certificate but i cant still get an push on background

**Comment by raviLakhtariya** [comment]
i could not get push notification banner

**Comment by raviLakhtariya** [comment]
when i am checking in simulator then i got notification like this :: only when conversion is open...but in background or if i close the conversion then could not get....and device i could not get notification which i sent you in screenshot....help me...in swift ios 
![Simulator Screen Shot - iPhone 8 Plus - 2019-05-31 at 10 31 52](https://user-images.githubusercontent.com/37133003/58682796-a0a15380-838f-11e9-84b7-8809d08c0403.png)

**Comment by raviLakhtariya** [comment]
Hi i am getting an issue in fresh chat notification … i could not get notification while app in background… and still not getting any push notification while app in foreground and conversion is off.

i had already follow all instruction and use your code demo which you had sent me yesterday…. in short total meaning is i am not getting any type of push… i had already sent screenshots…. in chat inbox ..Here is push notification is enabled : YES….some time if i create a new user then did not get sometime push notification enabled yes….

image





The second point after i get demo from you  and i had just set my bundle id in your projects but still i can’t get push in background in your demo projects…. 

also other push are working just only fresh chat push not getting in while app in background …and when conversion is off.. in simulator i got push like that :
![Screen Shot 2019-05-31 at 2 28 00 PM](https://user-images.githubusercontent.com/37133003/58695923-220add00-83b4-11e9-9e1f-cad46c893bfa.png)


but this notification i get when conversion is on :…..

but main issue this notification also do not get in device….what is actual problem can you share full demo of project…all type of code so i can get notification while app is in background….now solve this issue and guide me properly so i can get notification in background….while app is in background
![Simulator Screen Shot - iPhone 8 Plus - 2019-05-31 at 10 31 52](https://user-images.githubusercontent.com/37133003/58695944-2e8f3580-83b4-11e9-8bb3-9d8d65e7236b.png)


also create user and restore id and all think to share in code


which i had attached below..   i had also add this code but still does not work...attached below

""""""We checked you code, You are not requesting the user to register for notifications. I have added register for push notification function here : https://pastebin.com/16jzUJa7 Please call that method after initFreshchatSDK() in app delegate didFinishLaunchingWithOptions function.

 func registerNotifications()
    {
        if #available(iOS 10, *) {
            UNUserNotificationCenter.current().requestAuthorization(options:[.badge, .alert, .sound]){ (granted, error) in }
            UIApplication.shared.registerForRemoteNotifications()
        }
        else if #available(iOS 9, *) {
            UIApplication.shared.registerUserNotificationSettings(UIUserNotificationSettings(types: [.badge, .sound, .alert], categories: nil))
            UIApplication.shared.registerForRemoteNotifications()
        }
        else if #available(iOS 8, *) {
            UIApplication.shared.registerUserNotificationSettings(UIUserNotificationSettings(types: [.badge, .sound, .alert], categories: nil))
            UIApplication.shared.registerForRemoteNotifications()
        }
        else {
            UIApplication.shared.registerForRemoteNotifications(matching: [.badge, .sound, .alert])
        }
       
"""""""


and i already used demo of push which you sent me ...when i checked in device with my appp id it's does not work...

**Comment by harish-kumarc** [comment]
Hi @raviLakhtariya , 
As you are seeing a little delayed inapp banner on Freshchat screen(app screen attached) in simulator, that is not a push notification banner but actually a poller banner we display when device is not receiving any notification.

With agent portal screenshot attached, you could see the "Push Notification Enabled flag" on rhs is "Yes", that means the device token has been sent successfully with us or registering token `setPushRegistrationToken` api called successfully.

So only issue lies with receiving part, 
Can you please cross check if the certificate (.p12 file) is generated from Apple Push Services from keychain, like - 
<img width="363" alt="Screen Shot 2019-05-31 at 5 28 53 PM" src="https://user-images.githubusercontent.com/16202319/58704562-1cb88d00-83ca-11e9-84a1-a675c53a02d4.png">
Also please check validity of your certificate.
We have changed the sample with same snippets you attached and its able to receive push in both foreground and background states. Attaching here same.
Please write to support@freshchat.com if still you aren't able to fix. Our supports folks will help you to debug and fix. 
Thanks

[UNUserNotif_Push_Swift_Sample.zip](https://github.com/freshdesk/freshchat-ios/files/3241530/UNUserNotif_Push_Swift_Sample.zip)

**Comment by raviLakhtariya** [comment]
how much time need to get a push ...because With agent portal screenshot attached, you could see the "Push Notification Enabled flag" on rhs is "Yes",.....then still could not get any type of notification in device

**Comment by harish-kumarc** [comment]
HI @raviLakhtariya , After sending the message from Freshchat portal, you should receive your push instantly on SDK if everything is setup correctly. Can you verify other cautionary things mentioned in [message](https://github.com/freshdesk/freshchat-ios/issues/12#issuecomment-497721805). Also are you still not able to get any notification with new sample attached with same message?

**Comment by raviLakhtariya** [comment]
ok i had attached below... i had follow all the steps
![Screen Shot 2019-06-03 at 12 52 29 PM](https://user-images.githubusercontent.com/37133003/58783573-db5cf300-85fe-11e9-91de-d6bc794d47b2.png)

now i attached code---in app delegate what i done it.....there is other push is work...you need to check only freshchat code...if it correct? so why i am not getting push...??

[AppDelegate.swift.zip](https://github.com/freshdesk/freshchat-ios/files/3246338/AppDelegate.swift.zip)

**Comment by raviLakhtariya** [comment]
Or any other way to get push notification .....? i had sent you code in appdelegate swift. and when i register or login new user at that time.....i had write code like.....


    func createUser(){
        
        //  Freshchat.sharedInstance().identifyUser(withExternalID: CurrentTrip.shared.user.userId, restoreID: nil)
        let user = FreshchatUser.sharedInstance();
        
        user?.firstName = ProviderSingleton.shared.provider.firstName
        user?.lastName = ProviderSingleton.shared.provider.lastName
        user?.email = ProviderSingleton.shared.provider.email
        user?.phoneCountryCode = ProviderSingleton.shared.provider.countryPhoneCode
        user?.phoneNumber = ProviderSingleton.shared.provider.phone
        Freshchat.sharedInstance().setUser(user)
        NotificationCenter.default.addObserver(self, selector: #selector(self.methodOfReceivedNotification(notification:)), name: Notification.Name(FRESHCHAT_UNREAD_MESSAGE_COUNT_CHANGED), object: nil)
        
        
      //  Freshchat.sharedInstance().showConversations(self)
        // NotificationCenter.default.addObserver(self, selector: #selector(self.methodOfReceivedNotification(notification:)), name: Notification.Name(FRESHCHAT_ACTION_USER_ACTIONS), object: nil)
        
    }
    @objc func methodOfReceivedNotification(notification: Notification){
        Freshchat.sharedInstance().unreadCount { (count:Int) -> Void in
            print("Unread count (Async) :\(count)")
        }
    }



and i had create one icon button when i click on there then i only add like


:::Freshchat.sharedInstance().showConversations(self)

....anything else i need to do more?

**Comment by harish-kumarc** [comment]
Hi @raviLakhtariya ,
Your sample code (AppDelegate.swift) looks good and it works perfectly fine with sample app. So the issue is with certificate. Can you please check if you are applying the correct certificate with correct environment, i.e dev cert for development and prod for production(AppStore). Also make sure that `Production Certificate` checkbox should be `unchecked` in for development environment. 

Above snippet looks correct for implementation. Do let us know if you are able to fix it, if not please write to support@freshchat.com, we can go for screen share session to fix it.

**Comment by raviLakhtariya** [comment]
can you create video of your demo project which you had provide me. how you can get notification in your demo project. using swift 4 in freshchat integration

**Comment by raviLakhtariya** [comment]
can you send you certificate so i can check it ? its work or not

**Comment by harish-kumarc** [comment]
As we discussed over the call, the issue was related with an incorrect certificate. Please let us know if you have any issue after that.
Thanks

**Comment by miranhrupacki** [comment]
Hello guys, is it possible for ios sdk, when i call function showConversation, that user chat history stays saved for him whenever he enters app? Also, I can't manage to get history of my conversations, what am I doing wrong? I can send you my code how I set up my app. If you don't understand what i meant by that, just look picture of raviLakhtariya, he sent picture of inbox, thats what I want.
