### ISSUE TITLE
Customize In app banner

### ISSUE THREAD

**Issue by gkye** [freshdesk/freshchat-ios#14]
Would be nice to have an option to customize the in app banner being presented.

**Comment by harish-kumarc** [comment]
@gkye thanks for your suggestion : ). Sure we will look into that option too and keep you updated.

**Comment by harish-kumarc** [comment]
@gkye We supports complete customization of SDK screens and customizing **In-App Notification Banner** comes under **Notification** key in FCTheme.plist file. Complete theme guide is available [here](https://support.freshchat.com/solution/articles/229814-freshchat-ios-sdk-themes)
