### ISSUE TITLE
Core Data related crashes on iOS 12

### ISSUE THREAD

**Issue by lyubimovm** [freshdesk/freshchat-ios#18]
Crashes contains error messages:
```
Fatal Exception: NSInvalidArgumentException
+entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'KonotorConversation'
```
```
Fatal Exception: NSInvalidArgumentException
+entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FDParticipant'
```
```
Fatal Exception: NSInternalInconsistencyExceptionUnhandled error (NSCocoaErrorDomain, 256) occurred during faulting and was thrown: Error Domain=NSCocoaErrorDomain Code=256 "Не удалось открыть файл «Freshchat.sqlite». " UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/F4B6A782-A551-4BBD-AFFE-43157EF3B751/Library/Database/Freshchat.sqlite, NSSQLiteErrorDomain=23}
```
All users are on iOS 12. 
It is noteworthy that each user with crash have bunch of similar crashes

SDK version 1.4.6.
STR was not found :(
Full logs was sent to support@freshchat.com

**Comment by harish-kumarc** [comment]
Hi @lyubimovm , Thanks for the logs :). 
Logs refers to frailty in loading Freshchat core-data model. If possible can you please share the steps to replicate the crash. Please update SDK to 1.5+ as we have added some core-data changes, also try steps mentioned in [thread](https://github.com/freshdesk/freshchat-ios/issues/2#issuecomment-347426924) and let us know if the crash still persists. 
Thanks

**Comment by harish-kumarc** [comment]
We have done more enhancements with SDK [v2.5.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.5.2) to avoid coredata crashes.
