### ISSUE TITLE
Crash when freschatConfig.teamMemberInfoVisible = true

### ISSUE THREAD

**Issue by jnabhan** [freshdesk/freshchat-ios#20]
The chat widget is crashing when an agent who has a profile picture is assigned to a chat and when freschatConfig.teamMemberInfoVisible = true.
It seems to be happening after the profile picture gets downloaded. Otherwise, the chat is working perfectly fine.

Here is the full stacktrace:

2018-10-15 13:44:31.432470+0300 TestApplication[51142:7373672] +[UIImage fd_imageWithData:]: unrecognized selector sent to class 0x1175c0ae8
2018-10-15 13:44:31.521865+0300 TestApplication[51142:7373672] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIImage fd_imageWithData:]: unrecognized selector sent to class 0x1175c0ae8'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010783129b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000106c68735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010784fea4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000107835fb6 ___forwarding___ + 1446
	4   CoreFoundation                      0x0000000107837e88 _CF_forwarding_prep_0 + 120
	5   TestApplication                          0x00000001017a0c32 -[FDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] + 514
	6   TestApplication                          0x00000001017ff984 -[FDWebImageDownloader URLSession:task:didCompleteWithError:] + 113
	7   CFNetwork                           0x000000010ad5b8f2 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.241 + 284
	8   Foundation                          0x00000001066d319d __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	9   Foundation                          0x00000001066d30a4 -[NSBlockOperation main] + 68
	10  Foundation                          0x00000001066cfe13 -[__NSOperationInternal _start:] + 689
	11  Foundation                          0x00000001066d5e4a __NSOQSchedule_f + 227
	12  libdispatch.dylib                   0x000000010b8b15d1 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x000000010b8b263e _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010b8b5589 _dispatch_continuation_pop + 565
	15  libdispatch.dylib                   0x000000010b8b4963 _dispatch_async_redirect_invoke + 859
	16  libdispatch.dylib                   0x000000010b8c3028 _dispatch_root_queue_drain + 351
	17  libdispatch.dylib                   0x000000010b8c39cd _dispatch_worker_thread2 + 130
	18  libsystem_pthread.dylib             0x000000010bc9e169 _pthread_wqthread + 1387
	19  libsystem_pthread.dylib             0x000000010bc9dbe9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by harish-kumarc** [comment]
@jnabhan , Can you give us more context about the issue like which version of SDK and Xcode are you using for building your app and are you installing via cocoa pods or via drag and drop?

Thanks

**Comment by jnabhan** [comment]
I'm using version 1.5.5 of the SDK which I integrated by dragging and dropping the library since my project doesn't use Cocoa Pods. I'm building the project on Xcode 10.

Thanks

**Comment by harish-kumarc** [comment]
HI @jnabhan ,
For **Drag and Drop** addition of SDK along with Frameworks you have to set **-all_load**, **-objC** flags in Project Settings, **General -> Build Settings -> Other Linker flags**. We have mentioned same in integration [doc](https://support.freshchat.com/a/solutions/articles/232534) also. Please check and let us know if the issue is fixed :)

Thanks

**Comment by jnabhan** [comment]
@harish-kumarc, I added the flags you suggested to "Other Linker Flags" in the project settings but still got the same error. I'm also unable to open the link to the integration doc you provided.

**Comment by harish-kumarc** [comment]
Hi @jnabhan 
I have updated the link, its same integration doc only and in bottom we are adding above info for drag and drop case. Please clear derived data and check again and also if possible share a sample with us. Or if you want we will share one with you :). 

Thanks

**Comment by jnabhan** [comment]
@harish-kumarc unfortunately, clearing derived data did not fix the issue. I will create a test project that reproduces the issue and will link to it soon.

**Comment by jnabhan** [comment]
Hi @harish-kumarc 
I have uploaded the following project which reproduces the issue: https://github.com/jnabhan/FreshchatTest

Thanks

**Comment by harish-kumarc** [comment]
Hi @jnabhan ,
Thanks for sharing the demo app. We checked and as [mentioned](https://github.com/freshdesk/freshchat-ios/issues/20#issuecomment-431788745) you need to set **"-all_load"** for **other linker flags** in **Build Settings** for your project. We are attaching here same sample app with same change, do let us know if it works for you :)

Thanks
[FreshchatTest-master.zip](https://github.com/freshdesk/freshchat-ios/files/2511242/FreshchatTest-master.zip)

**Comment by jnabhan** [comment]
Thank you @harish-kumarc this is working now.
I am however terribly confused as to why it didn't work a couple of days ago. I may have been adding the argument to the wrong place.
