### ISSUE TITLE
Back button changes font size on highlight

### ISSUE THREAD

**Issue by ghost** [freshdesk/freshchat-ios#22]
Steps to reproduce:
 - use custom font for BackButtonStyle
 - start chat
 - attach image
 - before sending the image check "Back" button

The font for for the back button is set as following:
```
<key>BackButtonStyle</key>
<dict>
<key>fontName</key>
<string>Yantramanav-Light</string>
<key>textSize</key>
<string>16.0f</string>
<key>textColor</key>
<string>#000000</string>
</dict>
```

iOS version: iOS 12
Device: iPhone 7, iPhone XR

Normal state:
<img width="584" alt="normal state" src="https://user-images.githubusercontent.com/38656677/47677702-1ce87400-dbc0-11e8-9d83-ebfaad5c057f.png">
Highlighted state:
<img width="584" alt="highlighted state" src="https://user-images.githubusercontent.com/38656677/47677701-1c4fdd80-dbc0-11e8-8e23-5c8d6a0fd6d3.png">

**Comment by harish-kumarc** [comment]
Hi @sasha-tomorrow ,
We checked and are't able to reproduce issue on our side. Which version of Freshchat iOS SDK are you using for you app? Are you doing any alteration in font for you app when keyboard appears.

Thanks
Harish

**Comment by harish-kumarc** [comment]
Closing now, Please reopen if req.
