### ISSUE TITLE
back button color changed by UINavigationBar.appearance()

### ISSUE THREAD

**Issue by bestwnh** [freshdesk/freshchat-ios#23]
I used the FreshchatSDK (1.5.5) in my app, but my app set up the bar tine color and custom white back button image
<img width="551" alt="image" src="https://user-images.githubusercontent.com/1201345/48530531-08e88600-e8d3-11e8-8f7b-933aaa0fae37.png">
It cause the back button in Freshchat go white.
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1201345/48530455-c161fa00-e8d2-11e8-8436-5b3ad3bb376b.png">

For this situation in my custom view controller or some third-party framework(for example PayPal), I can reset the style for specific view controller like this:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/1201345/48530593-54029900-e8d3-11e8-8d16-1ad05ed23480.png">
<img width="837" alt="image" src="https://user-images.githubusercontent.com/1201345/48530671-a643ba00-e8d3-11e8-97a4-347ea02166cb.png">

But for Freshchat I can't find any way to do that, there is no public view controller class. Any solution?

**Comment by harish-kumarc** [comment]
Hi @bestwnh 
If you are setting any global values for Navigation bar and bar-button items, FreshchatSDK honours them so that users can have same UI experience as that of main app.  
If you you certainly wants to change tint color then before showing support(Freshchat) you can update tint color and revert back with viewDidAppear in same view controller.

Thanks

**Comment by bestwnh** [comment]
@harish-kumarc Unfortunately, I set up global values for both navigation bar and bar-button items, but in Freshchat UI, only the bar-button items effected. If you can make  Freshchat view controller keep all my global setup, it would be much better.

**Comment by hemanthFW** [comment]
Hi @bestwnh Thanks for reaching us out.

- Did you try changing the `textColor` values of the following key in theme file to your global values of navigation bar.
`<key>NavigationBar</key>
    <dict>
        <key>TitleTextStyle</key>
        <dict>
            <key>fontName</key>
            <string>SYS_DEFAULT_FONT_NAME</string>
            <key>textSize</key>
            <string>17.0f</string>
            <key>textColor</key>
            <string>#000000</string>
        </dict>
        <key>ActionButtonStyle</key>
        <dict>
            <key>fontName</key>
            <string>SYS_DEFAULT_FONT_NAME</string>
            <key>textSize</key>
            <string>16.0f</string>
            <key>textColor</key>
            <string>#0079FF</string>
        </dict>
        <key>NavigationBarStyle</key>
        <dict>
            <key>background</key>
            <string>#00000</string>
        </dict>
        <key>SubTitleTextStyle</key>
        <dict>
            <key>fontName</key>
            <string>SYS_DEFAULT_FONT_NAME</string>
            <key>textColor</key>
            <string>#6D6D6D</string>
        </dict>
    </dict>`

FYI, theme file will be in the `FCResources bundle` under the folder `Themes`.

**Comment by bestwnh** [comment]
@hemanthFW It works for you. Thank you.
