### ISSUE TITLE
React-native iOS push notification

### ISSUE THREAD

**Issue by vasyiok** [freshdesk/freshchat-ios#25]
Hello everyone! 
I am trying to setup push notifications in my app that is on react-native. I'm using react-native-freshchat-sdk and any the other feature works perfectly, but push notifications.

To serve push notifications I'm using react-native-push-notification and it works perfectly with my API.

Here is my code:
```
PushNotification.configure({
    onRegister: function(tokenObj) {
        const freshchatNotificationConfig = new FreshchatNotificationConfig();
        freshchatNotificationConfig.priority = FreshchatNotificationConfig.NotificationPriority.PRIORITY_HIGH;
        freshchatNotificationConfig.notificationSoundEnabled = true;
        Freshchat.setNotificationConfig(freshchatNotificationConfig);
        Freshchat.setPushRegistrationToken(tokenObj.token);
    },
    onNotification: function(incomeNotification) {
        // So here I see all my notifications. From my API and from Freshchat
        console.log(incomeNotification);
        Freshchat.isFreshchatNotification(incomeNotification, (freshchatNotification) => {
            if (freshchatNotification) {
                Freshchat.handlePushNotification(notification);
            } else {
                console.log(1111);
            }
        });
....
```

I'm checked my certificate, push token and it works with my API but I never get any notification from the Freshchat.

Maybe there is something wrong in my code and I'm doing something wrong? Any suggestions?

**Comment by MuthuFD** [comment]
Hi @vasyiok ,

Is this `console.log(incomeNotification);` console log getting printed?

Can you share us the printed log.

**Comment by vasyiok** [comment]
@MuthuFD unfortunately `console.log(incomeNotification)` is never getting printed when I send a message from Freshchat. But I see the notifications from API. 
And this is a point that I don't get any push notifications from the Freshchat

**Comment by georgmay** [comment]
Same here, native iOS, we don't receive any push notifications.

**Comment by hemanthFW** [comment]
@vasyiok @georgmay
 Please take a look into our Sample app
https://rnfreshchatsdk.firebaseapp.com/sample/SampleApp.zip
Use your AppId and App key in index.js. 
Hope you have updated iOS push notification p12 certificate in web portal.
**If iOS Certificate is not uploaded into our web portal,
login to our web portal go to Settings -> Mobile SDKs**
under APNS Push Certificate iOS upload your certificate and fill in your certificate password and application bundled.
