### ISSUE TITLE
String Localization does not affect immediately

### ISSUE THREAD

**Issue by Binusz** [freshdesk/freshchat-ios#27]
Hi, 
I followed "String Customisations"  steps in your SDK integration guide. It works anyway however it does not affect immediately. 
Freshchat window appear firstly in english. The second time, it appears in selected language. I also trigger the following notification,  **NotificationCenter.default.post(name: NSNotification.Name(rawValue: "FRESHCHAT_USER_LOCALE_CHANGED"), object: self, userInfo: nil)**

SDK version: 2.1.0

**Comment by SanjithKanagavel** [comment]
Hi @Binusz ,

Looks like there is a mistake in documentation.  Should like the below :

`NotificationCenter.default.post(name: NSNotification.Name(rawValue: FRESHCHAT_USER_LOCALE_CHANGED), object: self, userInfo: nil)`

Can you try them with this again ?
