### ISSUE TITLE
Theme support with Carthage

### ISSUE THREAD

**Issue by rafaelescoffier** [freshdesk/freshchat-ios#29]
Hi there,

I am trying to customise theme using instructions provided here, [freshchat-ios-sdk-themes](https://support.freshchat.com/support/solutions/articles/229814-freshchat-ios-sdk-themes), but it is not working. 

I am using Carthage to generate the framework. When testing with cocoapods, everything works as expected.

Can you please confirm this issue?

Thanks in advance.

**Comment by harish-kumarc** [comment]
Hi @rafaelescoffier , To over-ride current theme its better to create custom theme.plist from FCtheme.plist and during init you have to specify that with config `config.themeName = @“Custom_theme_file"; `. An advantage of custom theme file is that it will retain all theme changes after SDK update also. Also you can use pre-alfa version of Carthage SDK [here](https://github.com/freshdesk/freshchat-ios/tree/carthage) for reference.
Thanks :)

**Comment by rafaelescoffier** [comment]
@harish-kumarc this was exactly what I did, and didn't work with Carthage :)

 Can you please check if you are able to load the custom theme file as a Carthage generated framework?

**Comment by harish-kumarc** [comment]
Hi @rafaelescoffier , Correct.. we checked and the Freshchat SDK's custom theme outside framework isn't applying for screens.
To achieve custom theme for Freshchat screens currently you have to edit theme file within the Framework itself. We will surely amend it in our future release 👍 
Thanks

**Comment by xieweizhi** [comment]
Hi @harish-kumarc , is this issue fixed in the latest release?

**Comment by harish-kumarc** [comment]
Hi @xieweizhi , We haven't yet upgrade the Carthage SDK. We will update you once its fixed.

**Comment by rafaelescoffier** [comment]
Hi @harish-kumarc , any updates on this?

**Comment by iangmaia** [comment]
No updates here @harish-kumarc ?

**Comment by harish-kumarc** [comment]
There is no changes with theme customisation, we are exploring possible options to achieve it.

**Comment by harish-kumarc** [comment]
With latest changes in Carthage (https://github.com/freshdesk/freshchat-ios/tree/carthage) now customization is possible  for SDK screens.
