### ISSUE TITLE
iOS 11 support with Carthage binary

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/freshchat-ios#30]
iOS 11 doesn't seem to be supported by the binaries in the Carthage branch (at least not for Simulator).
Can you please check and confirm?

Thanks!

**Comment by harishkumar-bits** [comment]
HI @iangmaia , yeah currently there are conflicts with simulator(s). We are analysing it from our side and surely update you over this.
Thanks

**Comment by rafaelescoffier** [comment]
@harish-kumarc did you really meant `surely update you over this`? :)

**Comment by harish-kumarc** [comment]
@rafaelescoffier , finally we have Carthage with latest SDK [v2.7.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.7.0). @iangmaia the issue is resolved, please test with available device(s) and simulator(s).
