### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException +entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FCParticipants' +[FCParticipants createWithInfo:inContext:]

### ISSUE THREAD

**Issue by qhccthanh** [freshdesk/freshchat-ios#32]
Fatal Exception: NSInvalidArgumentException +entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FCParticipants' +[FCParticipants createWithInfo:inContext:]

iOS 12 only

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1949a5ea4 __exceptionPreprocess
1  libobjc.A.dylib                0x193b75a50 objc_exception_throw
2  CoreData                       0x19754b108 -[NSAttributeDescription defaultValue]
3  CoreData                       0x1974e8b28 +[NSEntityDescription insertNewObjectForEntityForName:inManagedObjectContext:]
4  FoodyNowPartners               0x10299f024 +[FCParticipants createWithInfo:inContext:]
5  FoodyNowPartners               0x10299ef8c +[FCParticipants addParticipantWithInfo:inContext:]
6  FoodyNowPartners               0x10298a78c __55+[FCMessageServices fetchMessagesForSrc:andCompletion:]_block_invoke_2
7  libdispatch.dylib              0x1943dd6c8 _dispatch_call_block_and_release
8  libdispatch.dylib              0x1943de484 _dispatch_client_callout
9  libdispatch.dylib              0x1943bdb34 _dispatch_main_queue_callback_4CF$VARIANT$armv81
10 CoreFoundation                 0x194935ce4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
11 CoreFoundation                 0x194930bac __CFRunLoopRun
12 CoreFoundation                 0x1949300e0 CFRunLoopRunSpecific
13 GraphicsServices               0x196ba9584 GSEventRunModal
14 UIKitCore                      0x1c1cc4c00 UIApplicationMain
15 FoodyNowPartners               0x1024fb2e4 main (PushManager.swift:16)
16 libdyld.dylib                  0x1943eebb4 start
```

**Comment by harish-kumarc** [comment]
Hi @qhccthanh , Thanks for the logs :) . Is this happening in dev environment, if yes then it will be great to have steps to replicate. For production can you please forward us your AppStore link.
Thanks

**Comment by qhccthanh** [comment]
@harish-kumarc, Thanks for responding. The crash happen when opening app and user must delete app and reinstall again my application again for fixing.
Actually, This crash happening on production, I can't reproduce it. More information, I'm using newest version of FreshChat iOS SDK and AppstoreID: id1313125493

**Comment by harish-kumarc** [comment]
Thanks again @qhccthanh for the info. We are investigating the issue from our side and update you about it.

**Comment by harish-kumarc** [comment]
Hi @qhccthanh , New SDK version [v2.5.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.5.2) is out. Please try and do let us know if the crash issue is resolved.
