### ISSUE TITLE
Change Font Name

### ISSUE THREAD

**Issue by syedrazackimran** [freshdesk/freshchat-ios#33]
```
<key>fontName</key>
<string>Avenir-Medium</string>
<key>textSize</key>
<string>17.0f</string>
<key>textColor</key>
<string>#000000</string>
```

I try to change font name it's not affecting... kindly do needfully

**Comment by SanjithKanagavel** [comment]
@syedrazackimran Can you please confirm the font `Avenir-Medium` is being added to project with target being set.  Also please let us know if you're doing changes in custom theme plist file ?

**Comment by hemanth-sudarsan** [comment]
@syedrazackimran Hope this is resolved, closing it for now.
