### ISSUE TITLE
Can't change MessageReplyViewStyle.background

### ISSUE THREAD

**Issue by xieweizhi** [freshdesk/freshchat-ios#35]
I followed the [Doc](https://support.freshchat.com/support/solutions/articles/229814-freshchat-ios-sdk-themes) to change the `MessageReplyViewStyle` but won't work.

Here is what I did,
In the latest SwiftSample project, I changed the MessageReplyViewStyle.background to another color of FCTheme.plist. 

The result is:

![image](https://user-images.githubusercontent.com/1779863/54914763-b24e2100-4f30-11e9-91dc-c097b575c2f9.png)

I want to change the background to a flat-color background.

Something I did wrong, does the SDK support this kind of modification?

**Comment by SanjithKanagavel** [comment]
Hey @xieweizh 

Let me give you some suggestions : 

1. `MessageReplyViewStyle` is the outer view of input prompt,  changing `background` of that would look similar to above image.
2. `MessageReplyInputViewStyle` is the inner textView of input prompt. Changing it's `background` and `borderColor`.

Making the two suggestions would look like the one below :

<p align="center">
<img src="https://user-images.githubusercontent.com/9746842/54919724-8d08e500-4f27-11e9-9e11-18a5932d9a2d.png" width="200" height="400" /></p>

**Comment by xieweizhi** [comment]
@SanjithKanagavel  Thanks for your reply.

So it's possible to change the whole background to a flat-color style? 

![image](https://user-images.githubusercontent.com/1779863/54925167-bb4aec80-4f48-11e9-9de3-e5a908d59cca.png)

**Comment by SanjithKanagavel** [comment]
Yes @xieweizhi, Set colour value (eg : #FFF000)  to `ConversationDetail > MessageListStyle > background` in **FCTheme.plist**.

**Comment by xieweizhi** [comment]
@SanjithKanagavel , Thanks, this solves my question.
