### ISSUE TITLE
Event handling chat conversation

### ISSUE THREAD

**Issue by cahyofendhi** [freshdesk/freshchat-ios#36]
how to know when conversation page dismiss? after show conversation i want when back button clicked, activity is finish, but  i not found event handling of freshchat sdk

**Comment by harish-kumarc** [comment]
Hi @cahyofendhi , sorry for the delay. Currently only a few tracking events are available with Freshchat
 1. Notification received, 2. message sent, 3. screen viewed, 4.message received.  
You can listen them after registering for `FRESHCHAT_ACTION_USER_ACTIONS` into your ViewController like :

``` [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(listenFCEvent:)
                                                 name:FRESHCHAT_ACTION_USER_ACTIONS
                                               object:nil]; ```

``` - (void) listenFCEvent:(NSNotification *)notif {
    NSLog(@"====FC Event - %@ ====", notif.userInfo[@"action"]);
    // Do actions based on events
} ```

We are working over unifying them and update you once available :) 

Thanks

**Comment by harish-kumarc** [comment]
Hi @cahyofendhi  with new release[ v2.7.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.7.0) we have updated user events with richer meta and integration documentation can be accessible [here](https://support.freshchat.com/support/solutions/articles/50000000057-how-to-track-user-actions-happening-inside-freshchat-sdk)

**Comment by cahyofendhi** [comment]
okay thanks @harish-kumarc
