### ISSUE TITLE
Crash on iOS React Native

### ISSUE THREAD

**Issue by bensont1** [freshdesk/freshchat-ios#38]
Hi recently, I got this error when launching ANY freshchat operation on iOS only

```
2019-05-01 18:04:53.796 [fatal][tid:main] Exception '-[ConversationOptions mergeInOptions:]: unrecognized selector sent to instance 0x1c46380e0' was thrown while invoking showConversations on target RNFreshchatSdk with params (
)
callstack: (
...
...
```

The method used to cause the above exception is 
`Freshchat.showConversations();`

Anyone having the same issue?

**Comment by hemanthFW** [comment]
Hi @bensont1 as we discussed via support channel this is not a SDK issue. 
Shall we close this out.

**Comment by bensont1** [comment]
Yes it should be closed. Seems it was an issue with the navigation controller unrelated to Freschat SDK

**Comment by jesobreira** [comment]
> Anyone having the same issue?

I was having the same issue with Ionic. My problem is that I was trying to use an integer value for the externalId when doing identifyUser(). Even thought my application does use numeric user IDs, it has to be cast to string.

```Objective-C
-(void)identifyUserWithExternalID:(NSString *) externalID restoreID:(NSString *) restoreID;
```

```javascript
window.Freshchat.identifyUser({
            externalId: String(userId),
            restoreId: restoreId
}, freshchatData)
```

Doing this does not fail on Android but AppCrashed on iOS (using [freshchat-phonegap](https://github.com/techaffinity/freshchat-phonegap)).

Leaving this here just in case someone does the same mistake.
