### ISSUE TITLE
Integration on react native

### ISSUE THREAD

**Issue by herarya** [freshdesk/freshchat-ios#4]
hi guys,
How to integration react native

**Comment by tryprasannan** [comment]
@herarya We don't have an official wrapper for React Native at the moment. You can try writing a wrapper on top of our existing API of Native SDK. If you run into any specific trouble you can drop a line to support@freshchat.com

**Comment by MuthuFD** [comment]
Hi @herarya , We have release alpha version of our React Native SDK. 
Please refer here for documentation and sdk - https://rnfreshchatsdk.firebaseapp.com

**Comment by herarya** [comment]
@MuthuFD thanks bro , awesome

**Comment by MuthuFD** [comment]
Yes @Martian2Lee . We will be officially releasing react-native support in both GitHub and NPM. We will update in this thread when we release.

Currently we have an alpha version out. If you have any queries, please feel free to mail us at support@freshchat.com.

**Comment by gianpaj** [comment]
Looks great!
I managed to test it on the iOS 🎉 

<img src="https://thumbs.gfycat.com/SecondarySilentIlladopsis-size_restricted.gif" width="400">

looking forward to the Production release ;)

**Comment by shoaibmerchant** [comment]
@MuthuFD Hi I am trying to setup Freshchat SDK in iOS (without Cocoapods). Can you help me manual steps on linking it with the xcode project. I tried adding the .a file to Link Library and also add the xcodeproj. I also added the directory in the Header Search Paths. But it still keeps throwing linker errors such as 'Undefined symbols for the architecture x86_64'

**Comment by naiduasn** [comment]
@gianpaj do you this sample code in GitHub which you can share to simplify our initial setup process?

**Comment by gianpaj** [comment]
@naiduasn i basically followed the instructions on this website:
https://rnfreshchatsdk.firebaseapp.com/

The installation of the native parts is not actually that painful. Once you it, it's fine.

But sure, here is the `App.js` I edited after creating a project with `react-native init`:
https://gist.github.com/gianpaj/ee94ecc5860970fadb6c54a7f93df486

**Comment by El-Sy** [comment]
Hi @MuthuFD, is there any update on putting the latest alpha version on npm?

**Comment by atulmy** [comment]
Are we supposed to use this https://www.npmjs.com/package/react-native-freshchat-sdk? The source of it is uncertain. Can anyone confirm if this is an official release? Would rather not install from any other source than the official release.

**Comment by MuthuFD** [comment]
@atulmy It is not the official package.

Please find the official package here
https://rnfreshchatsdk.firebaseapp.com/

**Comment by adrianha** [comment]
Hi @MuthuFD ,
i can't get callback when restore id generated (Freshchat.EVENT_USER_RESTORE_ID_GENERATED). I also tried to send chat, but the event was not triggered. I'm using react-native-freshchat-sdk@0.57.0 and already registed the listener.

Any idea about this issue?

```javascript
import {
  Freshchat,
  FreshchatConfig,
} from 'react-native-freshchat-sdk';

Freshchat.init('appId', 'appKey');
Freshchat.addEventListener(
      Freshchat.EVENT_USER_RESTORE_ID_GENERATED,
      () => {
        Freshchat.getUser(async user => {
          try {
            if (user.restoreId) {
              await sendRestoreId(user.restoreId);
            }
          } catch (e) {
            console.log('requestUpdateRestoreId.error', e.message);
          }
        });
      },
    );
```

**Comment by hannseman** [comment]
Can you please put this package on npm and claim the name `react-native-freshchat-sdk`? It's a big security concern that you allow non-official package squat your package names.

**Comment by agoldis** [comment]
rnfreshchatsdk.firebaseapp.com is dead, who knows what's the current state of RN support?

**Comment by bockc** [comment]
@agoldis https://www.npmjs.com/package/react-native-freshchat-sdk
But I still have trouble getting it to work well.

**Comment by the-kenneth** [comment]
@MuthuFD Is this still being supported? Will there be typescript definitions also?
