### ISSUE TITLE
UI for user email input

### ISSUE THREAD

**Issue by JanC** [freshdesk/freshchat-ios#40]
Hi,
most of the chat / support SDK (e.g. Instabug, Helpshift ..) offer a UI where the user can input his/her name and e-mail address before starting a conversation.

While the FreshChat [FreshchatUser](http://cocoadocs.org/docsets/FreshchatSDK/1.0.2/Classes/FreshchatUser.html) object allows to input those programatically, it would be useful for an easier integration if SDK offers a such a  UI and persist the values.

Is such a feature planned?

**Comment by SanjithKanagavel** [comment]
@JanC , Thanks for the suggestion. 

We don't have any specific pre-form to collect user data. Instead, You can create a custom screen with the necessary fields and use `userProperties` to set the user details. Also, will take this to my product team for product Improvement.
