### ISSUE TITLE
How can i get close event ?

### ISSUE THREAD

**Issue by nb5053** [freshdesk/freshchat-ios#42]
How can i get close event ?

**Comment by harish-kumarc** [comment]
Hi @nb5053 , Currently we do not have any close event in FreshchatSDK. Can you please give us more context so we can help you better. 
Thanks

**Comment by harish-kumarc** [comment]
@nb5053 , With SDK release [v2.7.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.7.0) we have added more richer events for user actions. Please check more with documentation [here](https://support.freshchat.com/support/solutions/articles/50000000057-how-to-track-user-actions-happening-inside-freshchat-sdk).

**Comment by thongncvn** [comment]
Hi @harish-kumarc, I'm on v3.7.4 and still don't see support for close event. Is there any plan on adding this?

**Comment by harish-kumarc** [comment]
Hi @thongncvn , We don't have close event in SDK. Can you give us more context on your use case for "close" event.

**Comment by thongncvn** [comment]
@harish-kumarc sure. I'm implementing a chat head. When user taps on it, Freshchat modal will appear and the chat head disappears. When user close the modal, the chat head appears. In addition, the chat head is put on an overlay (wix/react-native-navigation's).

On Android this behavior is great. But on iOS, Freshchat modal appears but lies behind the chat head overlay, hence the chat head doesn't disappear. So I think with the event, we can programmatically toggle the chat head.

What do you think about this?

**Comment by thongncvn** [comment]
@harish-kumarc if Freshworks team has any further information or decision about this issue, please let me know. Many thanks!
