### ISSUE TITLE
Push Notifications not coming in iOS

### ISSUE THREAD

**Issue by sabarics** [freshdesk/freshchat-ios#43]
`func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)
    {
        Freshchat.sharedInstance().setPushRegistrationToken(deviceToken)
    }`

Push notification not received.
I am getting 

"deliveryError": "DeviceTokenNotForTopic",
   "apnsMessage": "SimpleApnsPushNotification [token=bb05d0a1bd5445d43f9006adff94aea330d35d42745f57e343fd71577545069a, payload={\"aps\":{\"badge\":1,\"alert\":{\"body\":\"{\\\"source\\\":\\\"freshchat_user\\\"}\"},\"sound\":\"default\"}}, invalidationTime=Wed Jul 17 00:00:00 UTC 2019, priority=IMMEDIATE, topic=com.zuper.pro, apns-collapse-id=null]",
   "exceptionMessage": ""
 }

**Comment by harish-kumarc** [comment]
@sabarics , `DeviceTokenNotForTopic` error refers to mismatch between bundleId of your application and the cert you have uploaded in Freshchat or either the selected environment is incorrect.

Can you please check the following items :
1. You are using correct certificate with correct bundleId.
2. You are selecting correct environment while uploading push certificate in Freshchat. For dev environment make sure “Production Environment“ checkbox should be unchecked and checked for production.
You can use Keystore explorer for both the checks and can download from [here](https://keystore-explorer.org/)

Please check above and do let us know if you are able to resolve the issue. If not then please write to support@freshchat.com, our support team will connect and help you in fixing the issue. 
Thanks

**Comment by sabarics** [comment]
Yes @harish-kumarc uploaded certificate is incorrect. Now I have uploaded correct certificate, its working.
