### ISSUE TITLE
Open particular chat channel when tapped on "Message us" 

### ISSUE THREAD

**Issue by ravirajw** [freshdesk/freshchat-ios#44]
When we showFAQs - on FAQs screen we see "Message us" button at bottom. When tapped on "Message us" button. We are navigated to conversation channels list screen.

How to directly open particular conversation channel when tapping on "Message us" button

**Comment by harish-kumarc** [comment]
Hi @ravirajw , Yes you can open a specific channel using FAQOptions's api `filterContactUsByTags` with specific channel tag(s) needs to pass as parameter. Please find sample code here : 
```FAQOptions *options = [FAQOptions new];
    [options filterContactUsByTags:@[@"your_chnal_tag"] withTitle:@"single_match_default_channel_name_available"];
    [[Freshchat sharedInstance]showFAQs:self withOptions:options];```

Please note that the same tag will be applied for all contactus/message us on FAQ screens.
Thanks

**Comment by ravirajw** [comment]
Hi @harish-kumarc worked. Thank you.
