### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException +entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FCConversations'

### ISSUE THREAD

**Issue by Lucodalack** [freshdesk/freshchat-ios#45]
Fatal Exception: NSInvalidArgumentException
+entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FCConversations'
ios 12 only 

`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1a0997ea0 __exceptionPreprocess
1  libobjc.A.dylib                0x19fb69a40 objc_exception_throw
2  CoreData                       0x1a353b108 -[NSAttributeDescription defaultValue]
3  FoodyNowPartners               0x1011646f8 +[FCConversations RetriveConversationForConversationId:]
4  FoodyNowPartners               0x101128a48 +[FCMessageServices processMessageResponse:]
5  FoodyNowPartners               0x101128464 __55+[FCMessageServices fetchMessagesForSrc:andCompletion:]_block_invoke_4
6  libdispatch.dylib              0x1a03d16c8 _dispatch_call_block_and_release
7  libdispatch.dylib              0x1a03d2484 _dispatch_client_callout
8  libdispatch.dylib              0x1a037e9b4 _dispatch_main_queue_callback_4CF$VARIANT$mp
9  CoreFoundation                 0x1a0927dd0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
10 CoreFoundation                 0x1a0922c98 __CFRunLoopRun
11 CoreFoundation                 0x1a09221cc CFRunLoopRunSpecific
12 GraphicsServices               0x1a2b99584 GSEventRunModal
13 UIKitCore                      0x1cda1d054 UIApplicationMain
14 FoodyNowPartners               0x100c42868 main + 17 (PushManager.swift:17)
15 libdyld.dylib                  0x1a03e2bb4 start`

we updated in the newest version 2.5.2, but still received some crash from CoreData

**Comment by harish-kumarc** [comment]
@Lucodalack  Thanks for reporting the issue, we are closely looking into it and notify you once we have a update over it. If possible can you please let us know if you have info about the crash state i.e if its happening on background or foreground state. Thanks

**Comment by Lucodalack** [comment]
sorry for lately reply, it's happened on background

**Comment by harish-kumarc** [comment]
No worries @Lucodalack , Thanks for the information.

**Comment by Lucodalack** [comment]
hey, do we have any update for this issue?

**Comment by Lucodalack** [comment]
Sorry if it bother you, but do we have plan for fix that issue

**Comment by harish-kumarc** [comment]
Hi @Lucodalack , no worries. The issues is fixed and we will map it with our releases after QA. It will be out by February.

**Comment by Lucodalack** [comment]
thanks alot

**Comment by harish-kumarc** [comment]
Hi @Lucodalack , We have fixed the the issue with release [v3.3.3](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.3.3). Please update to lastest SDK.
