### ISSUE TITLE
while pushing view controller, it's behaving weird.

### ISSUE THREAD

**Issue by Bathibabu** [freshdesk/freshchat-ios#46]
I used below code for pushing to chat screen,It is navigating to empty screen immediatel moving to chat screen.How can I prevent this behaviour(empty screen immediatel moving to chat screen).Could you please guide me.

```
 let chatVC = Freshchat.sharedInstance()?.getConversationsControllerForEmbed(with: options) 
 self.navigationController?.pushViewController(chatVC, animated: true)
```
[![IssueGif](https://user-images.githubusercontent.com/10724887/61771607-def64480-ae0d-11e9-9abb-6336cebad9bb.gif)](https://user-images.githubusercontent.com/10724887/61771607-def64480-ae0d-11e9-9abb-6336cebad9bb.gif)

**Comment by harish-kumarc** [comment]
@Bathibabu , The screen visible after calling ShowConversation api which is loading screen and its intended behaviour for embedded view controller. You can use recommended presented view style if you wants to avoid the loading behaviour where it will be available for first launch only.

**Comment by Bathibabu** [comment]
@harish-kumarc So there is one more major issue that we are facing where-in we are seeing this Close Button appearing instead of the back button, on the first time we launch the chat, when we are trying to simply push the chat window on the current navigation stack. And this Close doesn't seem to work even after clicking multiple times, post which I have to kill my App. Can you please look into this issue.
![Simulator Screen Shot - iPhone 7 - 2019-07-25 at 18 14 33](https://user-images.githubusercontent.com/10724887/61875631-b30bb980-af08-11e9-9f50-0a01013ddab4.png)


PS: I need to push the chat on the current stack instead of present

**Comment by harish-kumarc** [comment]
@Bathibabu , we tried but aren't able to replicate the "Close" button in push to nav stack style. Also can you confirm if you are not changing the nav bar global content. I am attaching a sample app here with both push and presented styles.
[SwiftSample.zip](https://github.com/freshdesk/freshchat-ios/files/3434939/SwiftSample.zip)

**Comment by Bathibabu** [comment]
@harish-kumarc In below scenarios I am able to see "close" button in chat screen.
<img width="661" alt="Screen Shot 2019-07-30 at 10 16 42 AM" src="https://user-images.githubusercontent.com/10724887/62101533-5a933e00-b2b3-11e9-8023-523a07f369fe.png">

**Comment by harish-kumarc** [comment]
@Bathibabu , can you please check view stack and also make sure that Freshchat view is added correctly. If possible please share a sample app with implementation, this will surly helps us to serve better.
