### ISSUE TITLE
Update Carthage with the latest changes

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/freshchat-ios#48]
The Carthage branch has been stale for almost 1 year, would be nice for it to get the updates from the latest release -- I guess it's just about updating the resources and the library binary in the `carthage` branch?

Thanks,
Ian

**Comment by harish-kumarc** [comment]
Thanks for the notification Ian :), We will surely update Carthage branch with latest SDK.

**Comment by milanstevanovic** [comment]
> Thanks for the notification Ian :), We will surely update Carthage branch with latest SDK.

"surely" means nothing, could you please give us some ETA?
We are paying you in order to use this product, and we deserve adequate support for the money that we pay.

**Comment by harish-kumarc** [comment]
@milanstevanovic , we understand your concern, we will prioritise this and update Carthage SDK by end of this Month. Thanks

**Comment by harish-kumarc** [comment]
We have updated Carthage with latest SDK v2.7.0.
