### ISSUE TITLE
The problem with initialization SDK in another thread.

### ISSUE THREAD

**Issue by akulinsky** [freshdesk/freshchat-ios#49]
I have the problem with initialization SDK in another thread.
![Screen Shot 2019-08-21 at 12 28 34](https://user-images.githubusercontent.com/580511/63421355-2114a500-c411-11e9-9e82-03973919d234.png)

**Comment by harish-kumarc** [comment]
Hi, @akulinsky can you give us more context about the issue you are facing. Ideally you can init SDK in didFinishLaunchingWithOption method of your AppDelegate or anywhere before calling solutions APIs.

**Comment by harish-kumarc** [comment]
Closing the issue, please let us know if you are facing it again.
