### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by wbison** [freshdesk/freshchat-ios#5]
The FreshChat framework uses symbols without prefix causing duplicate symbol errrors, such as these about type 'Message' which is used in our app:

> duplicate symbol _OBJC_CLASS_$_Message in:
>  /Users/wbison/Library/Developer/Xcode/DerivedData/HarkPad-cvhryogxaryjrheibjeoyekxtyab/Build/Intermediates.noindex/HarkPad.build/Debug-iphonesimulator/HarkPad.build/Objects-normal/x86_64/Message.o
>  /Users/wbison/Documents/Dev/HarkPad/Pods/FreshchatSDK/FreshchatSDK/libFDFreshchatSDK.a(Message.o)
> duplicate symbol _OBJC_METACLASS_$_Message in:
>  /Users/wbison/Library/Developer/Xcode/DerivedData/HarkPad-cvhryogxaryjrheibjeoyekxtyab/Build/Intermediates.noindex/HarkPad.build/Debug-iphonesimulator/HarkPad.build/Objects-normal/x86_64/Message.o
>  /Users/wbison/Documents/Dev/HarkPad/Pods/FreshchatSDK/FreshchatSDK/libFDFreshchatSDK.a(Message.o)
> ld: 2 duplicate symbols for architecture x86_64

**Comment by harish-kumarc** [comment]
Thanks for bringing this to our notice, we will fix this in a subsequent release. If you can't wait, I would recommend you to update your class' name.

**Comment by harish-kumarc** [comment]
@wbison , We have fixes the **Duplicate Symbols** class issue with our latest SDK release [v1.5.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v1.5.0) :). Please update and let us know. Thanks
