### ISSUE TITLE
UIWebview usage warning when submitting app

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/freshchat-ios#50]
We're getting the following warning when submitting an app using the latest version of the FreshchatSDK:

>ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

We don't use many other third party libraries, so we're guessing it might be the case for Freshchat SDK that UIWebView is being referenced somewhere.

Can you guys please check and confirm if this happens or not? 
Thanks!

**Comment by harish-kumarc** [comment]
Hi @iangmaia , Thanks for reporting it. 
We are using UIWebView for loading selected article content. We acknowledge and push req. changes with our next release.

**Comment by harish-kumarc** [comment]
@iangmaia , UIWebView depreciated warning during AppStore is fixed with release [v2.7.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.7.2)

**Comment by iangmaia** [comment]
Great, thanks @harish-kumarc .
