### ISSUE TITLE
Crash Fatal Exception: NSInvalidArgumentException +entityForName: nil

### ISSUE THREAD

**Issue by AtifSharaf** [freshdesk/freshchat-ios#51]
I am getting below crashes. I am using v 2.4.3

Below is log

Fatal Exception: NSInvalidArgumentException
+entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FCConversations'

#0. Crashed: com.twitter.crashlytics.ios.exception
0  App                       0x1046c66cc CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  App                       0x1046c6ab4 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  App                       0x1046b6438 CLSHandler + 26 (CLSHandler.m:26)
3  App                       0x1046c4ce0 __CLSExceptionRecord_block_invoke + 199 (CLSException.mm:199)
4  libdispatch.dylib              0x22fde1888 <redacted> + 20
5  (Missing)                      0x5e45822fdee404 (Missing)
6  (Missing)                      0x6d7b81046c477c (Missing)
7  App                       0x1046c45b0 CLSExceptionRecordNSException + 102 (CLSException.mm:102)
8  App                       0x1046c41cc CLSTerminateHandler() + 259 (CLSException.mm:259)
9  libc++abi.dylib                0x22f5cc9cc <redacted> + 20
10 (Missing)                      0x1124822f5cca40 (Missing)
11 (Missing)                      0x6813022fde189c (Missing)
12 (Missing)                      0x69f4022fded73c (Missing)
13 (Missing)                      0x42698230362734 (Missing)
14 (Missing)                      0x67af023035d3e4 (Missing)
15 (Missing)                      0x332f023035c964 (Missing)
16 (Missing)                      0x242e823259dd8c (Missing)
17 (Missing)                      0x39b3825d7fd758 (Missing)
18 (Missing)                      0x3b6f81044eadcc (Missing)
19 libdyld.dylib                  0x22fe18fd8 <redacted> + 4

--

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x2303d2ab8 (Missing)
1  libobjc.A.dylib                0x22f5d7d00 (Missing)
2  CoreData                       0x232f02868 (Missing)
3  App                       0x1045e01e4 +[FCConversations RetriveConversationForConversationId:]
4  App                       0x1045a4870 +[FCMessageServices processMessageResponse:]
5  App                       0x1045a428c __55+[FCMessageServices fetchMessagesForSrc:andCompletion:]_block_invoke_4
6  libdispatch.dylib              0x22fde0308 (Missing)
7  libdispatch.dylib              0x22fde1888 (Missing)
8  libdispatch.dylib              0x22fded73c (Missing)
9  CoreFoundation                 0x230362734 (Missing)
10 CoreFoundation                 0x23035d3e4 (Missing)
11 CoreFoundation                 0x23035c964 (Missing)
12 GraphicsServices               0x23259dd8c (Missing)
13 UIKitCore                      0x25d7fd758 (Missing)
14 App                       0x1044eadcc main + 25 (ErrorLoadingCategoryCell.swift:25)
15 libdyld.dylib                  0x22fe18fd8 (Missing)

#0. Crashed: com.twitter.crashlytics.ios.exception
0  App                       0x1046c66cc CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  App                       0x1046c6ab4 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  App                       0x1046b6438 CLSHandler + 26 (CLSHandler.m:26)
3  App                       0x1046c4ce0 __CLSExceptionRecord_block_invoke + 199 (CLSException.mm:199)
4  libdispatch.dylib              0x22fde1888 <redacted> + 20
5  (Missing)                      0x5e45822fdee404 (Missing)
6  (Missing)                      0x6d7b81046c477c (Missing)
7  App                       0x1046c45b0 CLSExceptionRecordNSException + 102 (CLSException.mm:102)
8  App                       0x1046c41cc CLSTerminateHandler() + 259 (CLSException.mm:259)
9  libc++abi.dylib                0x22f5cc9cc <redacted> + 20
10 (Missing)                      0x1124822f5cca40 (Missing)
11 (Missing)                      0x6813022fde189c (Missing)
12 (Missing)                      0x69f4022fded73c (Missing)
13 (Missing)                      0x42698230362734 (Missing)
14 (Missing)                      0x67af023035d3e4 (Missing)
15 (Missing)                      0x332f023035c964 (Missing)
16 (Missing)                      0x242e823259dd8c (Missing)
17 (Missing)                      0x39b3825d7fd758 (Missing)
18 (Missing)                      0x3b6f81044eadcc (Missing)
19 libdyld.dylib                  0x22fe18fd8 <redacted> + 4

#1. Thread
0  libsystem_kernel.dylib         0x22ff65b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x22ffddb7c _pthread_wqthread + 536
2  (Missing)                      0x5fe822ffe3dc4 (Missing)

#2. Thread
0  libsystem_kernel.dylib         0x22ff65b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x22ffddabc _pthread_wqthread + 344
2  (Missing)                      0x1214022ffe3dc4 (Missing)

#3. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x22ff59c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x22ff590e8 mach_msg + 76
2  (Missing)                      0x47fd0230362520 (Missing)
3  (Missing)                      0x432023035d1c4 (Missing)
4  (Missing)                      0xab5023035c964 (Missing)
5  (Missing)                      0x139b8230d3da1c (Missing)
6  (Missing)                      0x10018230d3d8a4 (Missing)
7  (Missing)                      0x5d47025d8e936c (Missing)
8  (Missing)                      0x21c90230d3c61c (Missing)
9  (Missing)                      0x209f8230e72c54 (Missing)
10 (Missing)                      0x4034822ffdb908 (Missing)
11 (Missing)                      0x2b4c822ffdb864 (Missing)
12 (Missing)                      0x2aba022ffe3dcc (Missing)

#4. Thread
0  libsystem_pthread.dylib        0x22ffe3dc0 pthread_dependency_wait_np + 254

#5. io.branch.sdk.network.queue (QOS: USER_INTERACTIVE)
0  libsystem_kernel.dylib         0x22ff659c4 __ulock_wait + 8
1  libdispatch.dylib              0x22fde223c <redacted> + 60
2  (Missing)                      0x78ad822fde237c (Missing)
3  (Missing)                      0x2506822fdee6c0 (Missing)
4  (Missing)                      0x18ee822fdee2a8 (Missing)
5  (Missing)                      0x7a4b0104f60b74 (Missing)
6  Branch                         0x104f61748 BranchClassInitializeLog + 46692
7  Branch                         0x104f4a32c BNCURLForBranchDirectory_Unthreaded + 6436
8  Branch                         0x104f4439c BNCLogInitialize + 5364
9  CFNetwork                      0x2309afb9c <redacted> + 40
10 (Missing)                      0x660482309c4480 (Missing)
11 (Missing)                      0x3c440230e50288 (Missing)
12 (Missing)                      0x3a018230d55598 (Missing)
13 (Missing)                      0x56e20230d54a28 (Missing)
14 (Missing)                      0x593c0230e52044 (Missing)
15 (Missing)                      0x27de022fdedfac (Missing)
16 (Missing)                      0x6dde022fde1888 (Missing)
17 (Missing)                      0x3531822fde4880 (Missing)
18 (Missing)                      0x3daf022fde3f4c (Missing)
19 (Missing)                      0x40d822fdf0870 (Missing)
20 (Missing)                      0x31d9022fdf10f0 (Missing)
21 (Missing)                      0x36a0022ffddb38 (Missing)
22 (Missing)                      0x6663822ffe3dc4 (Missing)

#6. Thread
0  libsystem_kernel.dylib         0x22ff65b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x22ffddabc _pthread_wqthread + 344
2  (Missing)                      0x587b022ffe3dc4 (Missing)

#7. Thread
0  libsystem_kernel.dylib         0x22ff65b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x22ffddabc _pthread_wqthread + 344
2  (Missing)                      0x7ba1822ffe3dc4 (Missing)

#8. Thread
0  libsystem_kernel.dylib         0x22ff65b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x22ffddb7c _pthread_wqthread + 536
2  (Missing)                      0x7349822ffe3dc4 (Missing)

#9. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x22ff59c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x22ff590e8 mach_msg + 76
2  (Missing)                      0x3f9601046b140c (Missing)
3  libsystem_pthread.dylib        0x22ffdb908 <redacted> + 132
4  (Missing)                      0x726d822ffdb864 (Missing)
5  (Missing)                      0x6456822ffe3dcc (Missing)

#10. Thread
0  libsystem_kernel.dylib         0x22ff65b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x22ffddabc _pthread_wqthread + 344
2  (Missing)                      0x472c822ffe3dc4 (Missing)

#11. Thread
0  libsystem_kernel.dylib         0x22ff65b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x22ffddb7c _pthread_wqthread + 536
2  (Missing)                      0x10e2822ffe3dc4 (Missing)

#12. JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x22ff64ed4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x22ffdf4d0 <redacted> + 632
2  (Missing)                      0x350f022f56c990 (Missing)
3  (Missing)                      0x5b0b023770f874 (Missing)
4  (Missing)                      0x7dde82377138c8 (Missing)
5  (Missing)                      0x57db8237713064 (Missing)
6  (Missing)                      0x12148237714a8c (Missing)
7  (Missing)                      0x7934822ffdb908 (Missing)
8  (Missing)                      0xa88022ffdb864 (Missing)
9  (Missing)                      0x4c29822ffe3dcc (Missing)

#13. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x22ff59c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x22ff590e8 mach_msg + 76
2  (Missing)                      0x64630230362520 (Missing)
3  (Missing)                      0x12ca823035d1c4 (Missing)
4  (Missing)                      0x4fbf023035c964 (Missing)
5  (Missing)                      0x1d76023097fc88 (Missing)
6  (Missing)                      0x36570230d3c61c (Missing)
7  (Missing)                      0x676a8230e72c54 (Missing)
8  (Missing)                      0x25c6022ffdb908 (Missing)
9  (Missing)                      0x9f0822ffdb864 (Missing)
10 (Missing)                      0x78b0822ffe3dcc (Missing)

**Comment by harish-kumarc** [comment]
@AtifSharaf , Thanks for the detailed log. We are investigating issue(s) and update you about the progress. Need some more details like crash state i.e is it happening in background or forground state and is it replicable, if yes then please share steps to create.
Also we made db files accessible permission changes and some CoreData fixes with release v2.5.2 so please upgrade to latest SDK version.
Thanks

**Comment by AtifSharaf** [comment]
I have updated app with the latest SDK v2.7.1. 
I can't reproduce these crashes at my end, but it seems to be fixed since I haven't got crash for this issue for the updated app.
