### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException +entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FCParticipants'

### ISSUE THREAD

**Issue by AtifSharaf** [freshdesk/freshchat-ios#52]
Application crashes for some users

Fatal Exception: NSInvalidArgumentException
+entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name 'FCParticipants'

# OS Version: 12.4.1 (16G102)
# Device: iPhone XS Max
# RAM Free: 11.8%
# Disk Free: 60.6%

#0. Crashed: com.twitter.crashlytics.ios.exception
0  App                       0x1002a26cc CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  App                       0x1002a2ab4 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  App                       0x100292438 CLSHandler + 26 (CLSHandler.m:26)
3  App                       0x1002a0ce0 __CLSExceptionRecord_block_invoke + 199 (CLSException.mm:199)
4  libdispatch.dylib              0x21d5cd888 <redacted> + 20
5  (Missing)                      0x25e6821d5da404 (Missing)
6  (Missing)                      0x7d2f01002a077c (Missing)
7  App                       0x1002a05b0 CLSExceptionRecordNSException + 102 (CLSException.mm:102)
8  App                       0x1002a01cc CLSTerminateHandler() + 259 (CLSException.mm:259)
9  libc++abi.dylib                0x21cdb89cc <redacted> + 20
10 (Missing)                      0x4426021cdb8a40 (Missing)
11 (Missing)                      0x31fb021d5cd89c (Missing)
12 (Missing)                      0x1e9a821d5d973c (Missing)
13 (Missing)                      0x696b821db4e734 (Missing)
14 (Missing)                      0x1c20021db493e4 (Missing)
15 (Missing)                      0x86021db48964 (Missing)
16 (Missing)                      0x4557821fd89d8c (Missing)
17 (Missing)                      0x3ce2824afe9758 (Missing)
18 (Missing)                      0x3b9181000c6dcc (Missing)
19 libdyld.dylib                  0x21d604fd8 <redacted> + 4

--

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x21dbbeab8 (Missing)
1  libobjc.A.dylib                0x21cdc3d00 (Missing)
2  CoreData                       0x2206ee868 (Missing)
3  CoreData                       0x22068bcf4 (Missing)
4  App                       0x100194794 +[FCParticipants createWithInfo:inContext:]
5  App                       0x1001946fc +[FCParticipants addParticipantWithInfo:inContext:]
6  App                       0x10017ffc4 __55+[FCMessageServices fetchMessagesForSrc:andCompletion:]_block_invoke_2
7  libdispatch.dylib              0x21d5cc308 <redacted>
8  libdispatch.dylib              0x21d5cd888 (Missing)
9  libdispatch.dylib              0x21d5d973c (Missing)
10 CoreFoundation                 0x21db4e734 (Missing)
11 CoreFoundation                 0x21db493e4 (Missing)
12 CoreFoundation                 0x21db48964 (Missing)
13 GraphicsServices               0x21fd89d8c (Missing)
14 UIKitCore                      0x24afe9758 (Missing)
15 App                       0x1000c6dcc main + 25 (ErrorLoadingCategoryCell.swift:25)
16 libdyld.dylib                  0x21d604fd8 <redacted>

#0. Crashed: com.twitter.crashlytics.ios.exception
0  App                       0x1002a26cc CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  App                       0x1002a2ab4 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  App                       0x100292438 CLSHandler + 26 (CLSHandler.m:26)
3  App                       0x1002a0ce0 __CLSExceptionRecord_block_invoke + 199 (CLSException.mm:199)
4  libdispatch.dylib              0x21d5cd888 <redacted> + 20
5  (Missing)                      0x25e6821d5da404 (Missing)
6  (Missing)                      0x7d2f01002a077c (Missing)
7  App                       0x1002a05b0 CLSExceptionRecordNSException + 102 (CLSException.mm:102)
8  App                       0x1002a01cc CLSTerminateHandler() + 259 (CLSException.mm:259)
9  libc++abi.dylib                0x21cdb89cc <redacted> + 20
10 (Missing)                      0x4426021cdb8a40 (Missing)
11 (Missing)                      0x31fb021d5cd89c (Missing)
12 (Missing)                      0x1e9a821d5d973c (Missing)
13 (Missing)                      0x696b821db4e734 (Missing)
14 (Missing)                      0x1c20021db493e4 (Missing)
15 (Missing)                      0x86021db48964 (Missing)
16 (Missing)                      0x4557821fd89d8c (Missing)
17 (Missing)                      0x3ce2824afe9758 (Missing)
18 (Missing)                      0x3b9181000c6dcc (Missing)
19 libdyld.dylib                  0x21d604fd8 <redacted> + 4

#1. com.apple.root.default-qos
0  libsystem_kernel.dylib         0x21d7519c4 __ulock_wait + 8
1  libdispatch.dylib              0x21d5ce23c <redacted> + 60
2  (Missing)                      0x6a11821d5ce1a0 (Missing)
3  (Missing)                      0x58b1021d5cec78 (Missing)
4  (Missing)                      0x217f81003cdbdc (Missing)
5  libdispatch.dylib              0x21d5cc308 <redacted> + 32
6  (Missing)                      0x71e3821d5cd888 (Missing)
7  (Missing)                      0x6c5a021d5d04e0 (Missing)
8  (Missing)                      0x5cb9021d5dc870 (Missing)
9  (Missing)                      0x60b4821d5dd0f0 (Missing)
10 (Missing)                      0x3899821d7c9b38 (Missing)
11 (Missing)                      0x3709021d7cfdc4 (Missing)

#2. Thread
0  libsystem_kernel.dylib         0x21d751b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x21d7c9b7c _pthread_wqthread + 536
2  (Missing)                      0x4687021d7cfdc4 (Missing)

#3. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x21d745c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x21d7450e8 mach_msg + 76
2  (Missing)                      0x6666021db4e520 (Missing)
3  (Missing)                      0x62fb821db491c4 (Missing)
4  (Missing)                      0x4520821db48964 (Missing)
5  (Missing)                      0x3210021e529a1c (Missing)
6  (Missing)                      0x6723021e5298a4 (Missing)
7  (Missing)                      0x3b1d824b0d536c (Missing)
8  (Missing)                      0x736b021e52861c (Missing)
9  (Missing)                      0x7c18021e65ec54 (Missing)
10 (Missing)                      0x110e821d7c7908 (Missing)
11 (Missing)                      0x4b4b021d7c7864 (Missing)
12 (Missing)                      0x6639821d7cfdcc (Missing)

#4. Thread
0  libsystem_pthread.dylib        0x21d7cfdc0 pthread_dependency_wait_np + 254

#5. Thread
0  libsystem_kernel.dylib         0x21d751b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x21d7c9b7c _pthread_wqthread + 536
2  (Missing)                      0x41e2821d7cfdc4 (Missing)

#6. Thread
0  libsystem_pthread.dylib        0x21d7cfdc0 pthread_dependency_wait_np + 254

#7. Thread
0  libsystem_kernel.dylib         0x21d751b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x21d7c9abc _pthread_wqthread + 344
2  (Missing)                      0x676a821d7cfdc4 (Missing)

#8. Thread
0  libsystem_kernel.dylib         0x21d751b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x21d7c9abc _pthread_wqthread + 344
2  (Missing)                      0x6244821d7cfdc4 (Missing)

#9. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x21d745c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x21d7450e8 mach_msg + 76
2  (Missing)                      0x54a010028d40c (Missing)
3  libsystem_pthread.dylib        0x21d7c7908 <redacted> + 132
4  (Missing)                      0x2fd3821d7c7864 (Missing)
5  (Missing)                      0x565e821d7cfdcc (Missing)

#10. Thread
0  libsystem_kernel.dylib         0x21d751b64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x21d7c9b7c _pthread_wqthread + 536
2  (Missing)                      0x8bf821d7cfdc4 (Missing)

#11. JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x21d750ed4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x21d7cb4d0 <redacted> + 632
2  (Missing)                      0x4cd7821cd58990 (Missing)
3  (Missing)                      0x35f48224efb874 (Missing)
4  (Missing)                      0x24250224eff8c8 (Missing)
5  (Missing)                      0x4f048224eff064 (Missing)
6  (Missing)                      0x4d1b0224f00a8c (Missing)
7  (Missing)                      0x5ccc021d7c7908 (Missing)
8  (Missing)                      0x4e7c021d7c7864 (Missing)
9  (Missing)                      0x41cf021d7cfdcc (Missing)

#12. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x21d745c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x21d7450e8 mach_msg + 76
2  (Missing)                      0x3d9d021db4e520 (Missing)
3  (Missing)                      0x1abe021db491c4 (Missing)
4  (Missing)                      0x6dc7821db48964 (Missing)
5  (Missing)                      0xe82021e16bc88 (Missing)
6  (Missing)                      0x6119821e52861c (Missing)
7  (Missing)                      0x46ce021e65ec54 (Missing)
8  (Missing)                      0x41d021d7c7908 (Missing)
9  (Missing)                      0x236e821d7c7864 (Missing)
10 (Missing)                      0x2b96821d7cfdcc (Missing)

#13. Thread
0  libsystem_pthread.dylib        0x21d7cfdc0 pthread_dependency_wait_np + 254

#14. Thread
0  libsystem_pthread.dylib        0x21d7cfdc0 pthread_dependency_wait_np + 254

**Comment by harish-kumarc** [comment]
Hi @AtifSharaf , thanks for reporting the issue. If possible can you give us FreshchatSDK version no. where you are getting the crash as we have fix the issue with release[ v2.5.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.5.2). Also if you are on older version of SDK then please update with latest one.
Thanks

**Comment by AtifSharaf** [comment]
I am using v2.4.3 in the
Now I have updated to the latest. Hopefully, it will resolve crash since I can't reproduce crash at my end
