### ISSUE TITLE
Fatal exception: 'NSGenericException', reason: 'Access to UISearchBar's _searchField ivar is prohibited ...'

### ISSUE THREAD

**Issue by PavelStepanovTomorrow** [freshdesk/freshchat-ios#53]
Hey there! When implementing FAQ for our iOS app I've found a crash.

When I tap on search button in the FAQ section the app crashes. It happens in 100% cases for iOS 13. I know, that it's still in beta, but maybe it's something that you should check. For iOS 12 it works good.

I'm using FreshchatSDK (2.7.1)

Device:
iOS 13.1 (17A5831c)
iPhone SE

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UISearchBar's _searchField ivar is prohibited. This is an application bug'

On simulator it gives more info

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UISearchBar's _searchField ivar is prohibited. This is an application bug'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23afdbde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff5015cb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23afda1c +[NSException raise:format:] + 188
	3   UIKitCore                           0x00007fff465ed31b -[UISearchBar _searchField] + 49
	4   Foundation                          0x00007fff255796ef -[NSObject(NSKeyValueCoding) valueForKey:] + 317
	5   Debug                               0x0000000104446a7e -[FCSearchViewController setupSubviews] + 622
	6   Debug                               0x000000010444623b -[FCSearchViewController viewDidLoad] + 67
	7   UIKitCore                           0x00007fff4689f622 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 83
	8   UIKitCore                           0x00007fff468a4533 -[UIViewController loadViewIfRequired] + 1084
	9   UIKitCore                           0x00007fff468a4950 -[UIViewController view] + 27
	10  UIKitCore                           0x00007fff4681531e -[UINavigationController preferredContentSize] + 187
	11  UIKitCore                           0x00007fff467ba292 -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	12  UIKitCore                           0x00007fff467b6165 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.452 + 178
	13  UIKitCore                           0x00007fff46f12702 _runAfterCACommitDeferredBlocks + 352
	14  UIKitCore                           0x00007fff46f034e4 _cleanUpAfterCAFlushAndRunDeferredBlocks + 248
	15  UIKitCore                           0x00007fff46f32b16 _afterCACommitHandler + 85
	16  CoreFoundation                      0x00007fff23a5feb7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	17  CoreFoundation                      0x00007fff23a5a94e __CFRunLoopDoObservers + 430
	18  CoreFoundation                      0x00007fff23a5afca __CFRunLoopRun + 1514
	19  CoreFoundation                      0x00007fff23a5a6b6 CFRunLoopRunSpecific + 438
	20  GraphicsServices                    0x00007fff38016bb0 GSEventRunModal + 65
	21  UIKitCore                           0x00007fff46f0990f UIApplicationMain + 1621
	22  Debug                               0x00000001040bdb5b main + 75
	23  libdyld.dylib                       0x00007fff50fe1cf5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Thanks in advance

**Comment by harish-kumarc** [comment]
@PavelStepanovTomorrow thanks for reporting it. We are looking into it and update soon.

**Comment by harish-kumarc** [comment]
@PavelStepanovTomorrow , We have fixed the issue with release v2.7.2 (https://github.com/freshdesk/freshchat-ios/releases/tag/v2.7.2). Please update to latest SDK version and let us know if the change fixes the crash on your side.

**Comment by PavelStepanovTomorrow** [comment]
@harish-kumarc Works now, thank you 👍
