### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by AtifSharaf** [freshdesk/freshchat-ios#55]
Using SDK v2.4.3

# Platform: ios
# Version: 3.14.10
# Date: 2019-09-09T08:32:00Z
# OS Version: 12.4.0 (16G77)
# Device: iPhone 6 Plus
# RAM Free: 3.7%
# Disk Free: 7.9%

#0. Crashed: com.twitter.crashlytics.ios.exception
0  App                       0x100d0e6cc CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  App                       0x100d0eab4 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  App                       0x100cfe438 CLSHandler + 26 (CLSHandler.m:26)
3  App                       0x100d0cce0 __CLSExceptionRecord_block_invoke + 199 (CLSException.mm:199)
4  libdispatch.dylib              0x2314897d4 _dispatch_client_callout + 16
5  libdispatch.dylib              0x231437c1c _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  App                       0x100d0c77c CLSExceptionRecord + 206 (CLSException.mm:206)
7  App                       0x100d0c5b0 CLSExceptionRecordNSException + 102 (CLSException.mm:102)
8  App                       0x100d0c1cc CLSTerminateHandler() + 259 (CLSException.mm:259)
9  libc++abi.dylib                0x230c18838 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x230c188c4 std::terminate() + 84
11 libdispatch.dylib              0x2314897e8 _dispatch_client_callout + 36
12 libdispatch.dylib              0x231437008 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1068
13 CoreFoundation                 0x2319dc32c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation                 0x2319d7264 __CFRunLoopRun + 1924
15 CoreFoundation                 0x2319d67c0 CFRunLoopRunSpecific + 436
16 GraphicsServices               0x233bd779c GSEventRunModal + 104
17 UIKitCore                      0x25e355c38 UIApplicationMain + 212
18 App                       0x100b32dcc main + 25 (ErrorLoadingCategoryCell.swift:25)
19 libdyld.dylib                  0x23149a8e0 start + 4

--

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x231a4a98c __exceptionPreprocess
1  libobjc.A.dylib                0x230c239f8 objc_exception_throw
2  CoreFoundation                 0x2319c43f8 _CFArgv
3  CoreFoundation                 0x23194c0b8 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
4  CoreFoundation                 0x23193cc94 +[NSDictionary dictionaryWithObjects:forKeys:count:]
5  App                       0x100c591b0 -[FCMessageController updateBottomViewWith:andHeight:]
6  App                       0x100c5e5f4 -[FCMessageController updateBottomViewAfterCSATSubmisssion]
7  App                       0x100c5a388 __35-[FCMessageController checkChannel]_block_invoke
8  App                       0x100c5a97c __36-[FCMessageController checkChannel:]_block_invoke
9  CoreData                       0x2345de2b0 developerSubmittedBlockToNSManagedObjectContextPerform
10 libdispatch.dylib              0x2314897d4 _dispatch_client_callout
11 libdispatch.dylib              0x231437008 _dispatch_main_queue_callback_4CF$VARIANT$mp
12 CoreFoundation                 0x2319dc32c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0x2319d7264 __CFRunLoopRun
14 CoreFoundation                 0x2319d67c0 CFRunLoopRunSpecific
15 GraphicsServices               0x233bd779c GSEventRunModal
16 UIKitCore                      0x25e355c38 UIApplicationMain
17 App                       0x100b32dcc main + 25 (ErrorLoadingCategoryCell.swift:25)
18 libdyld.dylib                  0x23149a8e0 start

#0. Crashed: com.twitter.crashlytics.ios.exception
0  App                       0x100d0e6cc CLSProcessRecordAllThreads + 376 (CLSProcess.c:376)
1  App                       0x100d0eab4 CLSProcessRecordAllThreads + 407 (CLSProcess.c:407)
2  App                       0x100cfe438 CLSHandler + 26 (CLSHandler.m:26)
3  App                       0x100d0cce0 __CLSExceptionRecord_block_invoke + 199 (CLSException.mm:199)
4  libdispatch.dylib              0x2314897d4 _dispatch_client_callout + 16
5  libdispatch.dylib              0x231437c1c _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  App                       0x100d0c77c CLSExceptionRecord + 206 (CLSException.mm:206)
7  App                       0x100d0c5b0 CLSExceptionRecordNSException + 102 (CLSException.mm:102)
8  App                       0x100d0c1cc CLSTerminateHandler() + 259 (CLSException.mm:259)
9  libc++abi.dylib                0x230c18838 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x230c188c4 std::terminate() + 84
11 libdispatch.dylib              0x2314897e8 _dispatch_client_callout + 36
12 libdispatch.dylib              0x231437008 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1068
13 CoreFoundation                 0x2319dc32c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation                 0x2319d7264 __CFRunLoopRun + 1924
15 CoreFoundation                 0x2319d67c0 CFRunLoopRunSpecific + 436
16 GraphicsServices               0x233bd779c GSEventRunModal + 104
17 UIKitCore                      0x25e355c38 UIApplicationMain + 212
18 App                       0x100b32dcc main + 25 (ErrorLoadingCategoryCell.swift:25)
19 libdyld.dylib                  0x23149a8e0 start + 4

#1. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a138 _pthread_wqthread + 340
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#2. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a138 _pthread_wqthread + 340
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#3. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x2315dc0f4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x2315db5a0 mach_msg + 72
2  CoreFoundation                 0x2319dc120 __CFRunLoopServiceMachPort + 236
3  CoreFoundation                 0x2319d7030 __CFRunLoopRun + 1360
4  CoreFoundation                 0x2319d67c0 CFRunLoopRunSpecific + 436
5  Foundation                     0x2323a4eac -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
6  Foundation                     0x2323a4d3c -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKitCore                      0x25e43b754 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x2324d1674 __NSThread__start__ + 984
9  libsystem_pthread.dylib        0x2316692c0 _pthread_body + 128
10 libsystem_pthread.dylib        0x231669220 _pthread_start + 44
11 libsystem_pthread.dylib        0x23166ccdc thread_start + 4

#4. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a1f8 _pthread_wqthread + 532
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#5. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a1f8 _pthread_wqthread + 532
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#6. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a138 _pthread_wqthread + 340
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#7. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a138 _pthread_wqthread + 340
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#8. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x2315dc0f4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x2315db5a0 mach_msg + 72
2  App                       0x100cf940c CLSMachExceptionServer + 180 (CLSMachException.c:180)
3  libsystem_pthread.dylib        0x2316692c0 _pthread_body + 128
4  libsystem_pthread.dylib        0x231669220 _pthread_start + 44
5  libsystem_pthread.dylib        0x23166ccdc thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a138 _pthread_wqthread + 340
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#10. Thread
0  libsystem_kernel.dylib         0x2315e7b74 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x23166a138 _pthread_wqthread + 340
2  libsystem_pthread.dylib        0x23166ccd4 start_wqthread + 4

#11. JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x2315e6ee4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x231661cf8 _pthread_cond_wait$VARIANT$mp + 636
2  libc++.1.dylib                 0x230bbd128 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 96
3  JavaScriptCore                 0x238c70304 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 124
4  JavaScriptCore                 0x238c701b4 std::__1::cv_status std::__1::condition_variable_any::wait_until<std::__1::unique_lock<bmalloc::Mutex>, std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<bmalloc::Mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 116
5  JavaScriptCore                 0x238c6ee4c bmalloc::Scavenger::threadRunLoop() + 296
6  JavaScriptCore                 0x238c6e54c bmalloc::Scavenger::Scavenger(std::__1::lock_guard<bmalloc::Mutex>&) + 10
7  JavaScriptCore                 0x238c6ff8c std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*) + 38
8  libsystem_pthread.dylib        0x2316692c0 _pthread_body + 128
9  libsystem_pthread.dylib        0x231669220 _pthread_start + 44
10 libsystem_pthread.dylib        0x23166ccdc thread_start + 4

#12. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x2315dc0f4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x2315db5a0 mach_msg + 72
2  CoreFoundation                 0x2319dc120 __CFRunLoopServiceMachPort + 236
3  CoreFoundation                 0x2319d7030 __CFRunLoopRun + 1360
4  CoreFoundation                 0x2319d67c0 CFRunLoopRunSpecific + 436
5  CFNetwork                      0x231ff074c -[__CoreSchedulingSetRunnable runForever] + 216
6  Foundation                     0x2324d1674 __NSThread__start__ + 984
7  libsystem_pthread.dylib        0x2316692c0 _pthread_body + 128
8  libsystem_pthread.dylib        0x231669220 _pthread_start + 44
9  libsystem_pthread.dylib        0x23166ccdc thread_start + 4

#13. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x2315dc0f4 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x2315db5a0 mach_msg + 72
2  CoreFoundation                 0x2319dc120 __CFRunLoopServiceMachPort + 236
3  CoreFoundation                 0x2319d7030 __CFRunLoopRun + 1360
4  CoreFoundation                 0x2319d67c0 CFRunLoopRunSpecific + 436
5  AVFAudio                       0x237948334 GenericRunLoopThread::Entry(void*) + 156
6  AVFAudio                       0x237972c60 CAPThread::Entry(CAPThread*) + 88
7  libsystem_pthread.dylib        0x2316692c0 _pthread_body + 128
8  libsystem_pthread.dylib        0x231669220 _pthread_start + 44
9  libsystem_pthread.dylib        0x23166ccdc thread_start + 4

**Comment by harish-kumarc** [comment]
@AtifSharaf , Can you please update SDK to [v3.2.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.2.2) and let us know if the issue is fixed.
