### ISSUE TITLE
App crashes +[FCConversations RetriveConversationForConversationId:] + 144

### ISSUE THREAD

**Issue by AtifSharaf** [freshdesk/freshchat-ios#56]
using v2.7.1

<img width="631" alt="Screen Shot 2019-09-17 at 12 15 03 PM" src="https://user-images.githubusercontent.com/11500668/65023916-e2590880-d944-11e9-950b-b0f2298fc878.png">

[DtMmfURWSR2sayCu4jjVub.xccrashpoint.zip](https://github.com/freshdesk/freshchat-ios/files/3620021/DtMmfURWSR2sayCu4jjVub.xccrashpoint.zip)

**Comment by harish-kumarc** [comment]
@AtifSharaf, We have made CoreData improvements in SDK [v3.2.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.2.2) please update SDK and let us know if the issue is fixed.
