### ISSUE TITLE
App Crash CoreData: -[NSFetchRequest(_NSInternalMethods) _resolveEntityWithContext:] + 84

### ISSUE THREAD

**Issue by AtifSharaf** [freshdesk/freshchat-ios#57]
using SDK v2.7.1

<img width="1247" alt="Screen Shot 2019-09-17 at 12 19 30 PM" src="https://user-images.githubusercontent.com/11500668/65024243-7d51e280-d945-11e9-8c3d-b3c2ab8eb9cd.png">
<img width="1263" alt="Screen Shot 2019-09-17 at 12 19 38 PM" src="https://user-images.githubusercontent.com/11500668/65024244-7d51e280-d945-11e9-8ade-b035f41f4838.png">

**Comment by harish-kumarc** [comment]
Hi @AtifSharaf , Thanks for the logs. Reported issue is link with CoreData, we are investigating the issue from our side and surly update you about it.

**Comment by AtifSharaf** [comment]
@harish-kumarc is their any update on this issue?

**Comment by harish-kumarc** [comment]
@AtifSharaf , we made some improvements to fix the issues. Can you please update SDK to [v3.2.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.2.2) and letus know if the issue is fixed.
