### ISSUE TITLE
Present Conversations in popup

### ISSUE THREAD

**Issue by wbison** [freshdesk/freshchat-ios#6]
I'd like to present the conversations in a popup on iPad:
```
    UIViewController *chat  = [[Freshchat sharedInstance] getConversationsControllerForEmbed];
    chat.modalPresentationStyle = UIModalPresentationFormSheet;
    chat.popoverPresentationController.sourceRect = self.view.bounds;
    chat.popoverPresentationController.sourceView = self.view;
    [self presentViewController:chat animated:NO completion:nil];
```

This shows a popup with "Loading Messages" and a spinning indicatorview.

What's the proper way to do this?

**Comment by harish-kumarc** [comment]
Hi @wbison 
Freshchat’s message screen UI isn’t fully resonate with popups so are not recommended. We will surely improve that in our later releases.  
To resolve the loading issue, you need add embedded Freshchat controller with UINavigationController and add that as childViewController in your popup view. For eg-
```
UIViewController *chat  = [[Freshchat sharedInstance] getConversationsControllerForEmbed];
UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:chat];
nav.view.frame = self.vc1.view.bounds;
[self.popVC.view addSubview:nav.view];
[self.popVC addChildViewController:nav];
[chat didMoveToParentViewController:self];
```
Thanks
