### ISSUE TITLE
Pushtoken is not submitted to server on iOS 13

### ISSUE THREAD

**Issue by TimE90** [freshdesk/freshchat-ios#60]
Hey!

I already submitted a ticket via support (#4501484). There is an iOS 13 issue with push tokens. Because NSData description has changed… if we compile the app on iOS 12 your server receives a pushtoken for the user but on iOS 13 it doesn't. You must update the SDK urgently!

The push works in iOS 12 but your backend says on iOS 13 users there is no push token. So please fix SDK for iOS 13 to post correct pushtoken to your server…

**Comment by PavelStepanovTomorrow** [comment]
Have the same problem, have come here to write it :)

**Comment by harish-kumarc** [comment]
Hi @PavelStepanovTomorrow @TimE90 .. We have identified the issue and pushing the new version with the fix asap. Will update you shortly with release version. Thanks

**Comment by TimE90** [comment]
Hi! Ok, thanks for fast fix! Please comment when we can update :)

**Comment by TimE90** [comment]
@harish-kumarc did you get it? We need your SDK update before submitting our app…

**Comment by TimE90** [comment]
@harish-kumarc What's the status?

**Comment by harish-kumarc** [comment]
HI @TimE90 ,Sorry the delay... The Fix is under QA cycle, will update you asap it is available in production. If you wants to verify the fix, our pre-prod version is available you can test via replacing pod 'FreshchatSDK' with below line in your podfile.
```
pod 'FreshchatSDK', :git => 'https://github.com/freshdesk/freshchat-ios', :branch => 'canary' 
```

Thanks

**Comment by TimE90** [comment]
@harish-kumarc Tested and it works! Thanks for fix!

**Comment by PavelStepanovTomorrow** [comment]
Works good, thank you, that was fast :)

**Comment by harish-kumarc** [comment]
@PavelStepanovTomorrow @TimE90 , production version is also live with [v2.8.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.8.0). Please check and let u know about that too :). Thanks

**Comment by TimE90** [comment]
@harish-kumarc ok, will switch back to production. We've submitted our app some hours ago with pre-pod version… anything different to production?

**Comment by PavelStepanovTomorrow** [comment]
> @PavelStepanovTomorrow @TimE90 , production version is also live with [v2.8.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.8.0). Please check and let u know about that too :). Thanks

I've checked it on the production already, works good

**Comment by harish-kumarc** [comment]
@TimE90 , Its just a branch difference rest all are same only. Just make sure to update to prod **pod 'FreshchatSDK'** in next release :)
