### ISSUE TITLE
iOS 13 theme ignored for setting navigation bar color

### ISSUE THREAD

**Issue by bobby-snap** [freshdesk/freshchat-ios#62]
The value I've set in my FCTheme.plist file for the navigation bar's background color appears to be getting ignored. I just installed the 2.8.1 update released yesterday in the hope that this would correct the issue, but it didn't have any effect. 

![image](https://user-images.githubusercontent.com/41586445/66676691-ad7f5f00-ec2d-11e9-9b2d-8e3bb10ad41c.png)

![Simulator Screen Shot - iPhone 11 Pro - 2019-10-11 at 13 46 04](https://user-images.githubusercontent.com/41586445/66676843-05b66100-ec2e-11e9-9a68-60e4325d6b4b.png)

As you can see, it should be white and the font colors are various shades of gray. Instead, the navigation bar is using what I've set as my default global appearance, which to illustrate the problem I've changed to red. Normally it's actually the same gray I'm using for the fonts here, which means it's all the same color and you can't see the text at all.

Setting the navigation bar's appearance has changed in iOS 13 to be set from the `UINavigationBarAppearance()` helper object, and for background specifically `UINavigationBarAppearance.backgroundColor`. Is this conversations view possibly still using the old style approach of setting `UINavigationBar.appearance().barTintColor`?

**Comment by harish-kumarc** [comment]
Hi @bobby-snap ,  Freshchat SDK always give preference to App's Navigation bar appearance means if you have applied a specific colour to your app's navigation bar and setting up universally (using UIAppearance APIs) then that will be applied for Freshchat SDK screens also, so you doesn't need to perform any changes to alter app's lookalike appearance. 
Yes we are still on old style approach and will move to latest in next release(s). 
With release v2.8.1 we have updated dark mode theme changes only.

**Comment by bobby-snap** [comment]
> Hi @bobby-snap , Freshchat SDK always give preference to App's Navigation bar appearance means if you have applied a specific colour to your app's navigation bar and setting up universally (using UIAppearance APIs) then that will be applied for Freshchat SDK screens also, so you doesn't need to perform any changes to alter app's lookalike appearance.

It previously did not behave this way in my experience prior to iOS 13. The universal appearance in my app has always been gray, but the Freshchat theme's white color was properly set instead. I rather thought that was the point of being able to set it in the theme file, to override whatever else your app may have set and for Freshchat's navigation bar, use the value in the theme.

**Comment by harish-kumarc** [comment]
Hi @bobby-snap , we haven't change anything other than dark mode theme in SDK related with navigation bar recently. Also please verify with older release(s), also if possible please share same version where you have observed the change. To install any specific version use - pod 'FreshchatSDK', 'Specific_SDK_Version'
Thanks

**Comment by bobby-snap** [comment]
It was Freshchat 2.8.0 that I found it on, and I just updated to see if it happened to be fixed in 2.8.1. Going back to an old version is not going to fix this, I am sure. If you haven't changed anything else related to the navigation bar recently, then that really is the source of the issue. I'm only trying to explain what's wrong so that it can be fixed. :)

So here's the full picture, of everything I can think might help to illustrate the change is an iOS 13 one and not adopting the new APIs.

I am configuring the universal appearance in my app delegate like so:
```
        let titleFontAttrs = [ NSAttributedString.Key.font: UIFont(name: "custom-font-name", size: 19)!, NSAttributedString.Key.foregroundColor: UIColor.white ]
        let barButtonFontAttrs = [ NSAttributedString.Key.font: UIFont(name: "custom-font-name", size: 12)! ]

        UINavigationBar.appearance().tintColor = UIColor.white // bar icons
        
        if #available(iOS 13.0, *) {
            let appearance = UINavigationBarAppearance()
            appearance.backgroundColor = .red
            
            appearance.titleTextAttributes = titleFontAttrs
            appearance.largeTitleTextAttributes = titleFontAttrs

            UINavigationBar.appearance().isTranslucent = false
            
            appearance.buttonAppearance.normal.titleTextAttributes = barButtonFontAttrs
            appearance.buttonAppearance.highlighted.titleTextAttributes = barButtonFontAttrs

            UINavigationBar.appearance().standardAppearance = appearance
            UINavigationBar.appearance().compactAppearance = appearance
            UINavigationBar.appearance().scrollEdgeAppearance = appearance
        } else {
            UINavigationBar.appearance().barTintColor = .red // bar background

            UINavigationBar.appearance().titleTextAttributes = titleFontAttrs

            UINavigationBar.appearance().isTranslucent = false

            UIBarButtonItem.appearance().setTitleTextAttributes(barButtonFontAttrs, for: .normal)
            UIBarButtonItem.appearance().setTitleTextAttributes(barButtonFontAttrs, for: .highlighted)
        }
```

Anywhere that I don't want this configuration, I have to make these adjustments from the view controller. This is what I believe needs updated in your SDK, to check for iOS 13 availability and adopt the new API. Using the old API for an app built in Xcode 11 on a device running iOS 13 means the appearance settings _will be ignored_.
```
    func setNavigationBarAppearance(withFont titleFontAttrs: [NSAttributedString.Key: Any], backgroundColor: UIColor) {

        if #available(iOS 13, *) {
            let appearance = UINavigationBarAppearance()
            appearance.backgroundColor = backgroundColor
            
            appearance.titleTextAttributes = titleFontAttrs
            appearance.largeTitleTextAttributes = titleFontAttrs

            navigationBar.standardAppearance = appearance
            navigationBar.compactAppearance = appearance
            navigationBar.scrollEdgeAppearance = appearance
        } else {
            navigationBar.barTintColor = backgroundColor

            navigationBar.titleTextAttributes = titleFontAttrs
        }
    }
```

I've updated the FCTheme.plist file to have a gold background color to also help show the difference:
![Screen Shot 2019-10-16 at 11 21 28 AM](https://user-images.githubusercontent.com/41586445/66938621-20f6e700-f007-11e9-8072-e758ce6ca224.png)

With the above theme plist and universal appearance being the same, and Freshchat SDK 2.8.0 installed in this case, here is my app running on an iOS 13 simulator:
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-16 at 11 22 16](https://user-images.githubusercontent.com/41586445/66938715-513e8580-f007-11e9-92dd-53bed50ef21e.png)

Now here it is on an iOS 12.2 simulator. Nothing in code changed from the above, but as you can see the theme is correctly followed.
![Simulator Screen Shot - iPhone Xs - 2019-10-16 at 11 24 00](https://user-images.githubusercontent.com/41586445/66938822-834fe780-f007-11e9-8cfb-0cee93b5dc7c.png)

Hopefully this paints a full picture now. You must update to the new appearance APIs, which isn't a terribly complicated change as I've shown above all you really need to do, otherwise it will be broken for anyone setting their own universal appearance that is different from the Freshchat theme.

**Comment by hemanth-sudarsan** [comment]
@bobby-snap Fixed this in our latest version.
Please update to the latest version.

**Comment by yasirtrimulabs** [comment]
Hi @bobby-snap can you tell me how did you change the message background to purple?
