### ISSUE TITLE
How to open FAQs on a specific entry?

### ISSUE THREAD

**Issue by jasontrask** [freshdesk/freshchat-ios#63]
I'd like to display the FAQs page in my app, but rather than filtering or letting the user search for an FAQ I'd like to be able to just display a specific FAQ immediately. Is this possible?

I thought that this might be what I'm looking for, but I can't seem to get it to work:
`-(void) openFreshchatDeeplink:(NSString *)linkStr viewController:(UIViewController *) viewController;`
I tried providing it with various forms of the FAQ URL in the `linkStr` param, but no luck (console logs: `Freshchat Error: Link not processed.`. Do you have an example of how this method should work?

**Comment by harish-kumarc** [comment]
Hi @jasontrask , 
To open Freshchat deeplinks via `openFreshchatDeeplink` api please follow deep link pattern as "freshchat://faq/article?article_id=ID_VAL"
Where ID_VAL is article id visible in web portal when specific article is opened.
Sample account URL : https://web.freshchat.com/a/XXXXXXXXXXX/faqs/45/articles/123 
Here 123 is ID_VAL

Another alternate option to directly open an FAQ is to call showFAQs API with FAQOptions, Please see documentation section for more info. - https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps
Thanks

**Comment by jasontrask** [comment]
Hi - thanks for the quick reply :)

I couldn't see anything in the FAQOptions which would allow a specific ID of an FAQ to be set...? The documentation just talks about setting filters.

Regarding the `openFreshchatDeeplink`, thanks - that pattern did the trick! But... this seems to only work with locally cached data? I can't get it to display the article until I've gone through the normal showFAQs API and browsed for the article manually. Only then will the `openFreshchatDeeplink` call display the single article. Is this a bug or am I doing something wrong?

**Comment by harish-kumarc** [comment]
Hi @jasontrask 
You can filter specific FAQ article(s) using FAQ tags. For that you need to mark/add specific tag for an article from web portal under FAQ sections . Please check section [4.2.1 Filtering FAQs](https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps) here.
We have a threshold value for fetching FAQ after last fetch, so if an article is updated and if user opens app with in that threshold time then FAQs won't get updated. So user won't able to see updated article. Also seems like same behaviour happens in your case. We are in the process of optimising this behaviour.
Thanks

**Comment by harish-kumarc** [comment]
We have optimise the FAQ behaviour for article list view and article detail view with release [v3.7.4](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.7.4). Please update to latest SDK.
