### ISSUE TITLE
Freshchat CoreData warning

### ISSUE THREAD

**Issue by AtifSharaf** [freshdesk/freshchat-ios#64]
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/CE6EBCBE-1F38-4E9A-BEA4-609659C25C4A/SharafDG.app/FreshchatModels.bundle/FreshchatModel.momd/FreshchatModel 5.omo'

It didn't cause any crash.
using SDK version: 2.8.1

**Comment by harish-kumarc** [comment]
hi @AtifSharaf , correct above one is warning with newer version of Xcode. It's not responsible for any crashes. We will clear with our coming release(s).

**Comment by harish-kumarc** [comment]
HI @AtifSharaf the console warning is fixed with release [v3.3.3](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.3.3)
