### ISSUE TITLE
CoreData Crash in release config

### ISSUE THREAD

**Issue by kinshukkashyap** [freshdesk/freshchat-ios#65]
In debug config , I get this warning and in release i get a crash regarding core data, since my app does not use core data , neither does any other dependencies, i am suspecting this could be an issue.

CoreData: annotation:  Failed to load optimized model at path '/Users/kinshuk/Library/Developer/CoreSimulator/Devices/EB29EE4C-89DB-4C58-A8B7-0C707766D245/data/Containers/Bundle/Application/04863779-4290-4B6F-9177-FB5EF2941DC6/Vantage Circle.app/FreshchatModels.bundle/FreshchatModel.momd/FreshchatModel 2.omo'

**Comment by harish-kumarc** [comment]
hi @kinshukkashyap , we are aware of the warning above and its actually not creating any crashes. We will clear it in our future release(s). Can you give us logs for the crash and also steps if you are able to replicate it.

**Comment by kinshukkashyap** [comment]
So far i have the only common pattern i see in this crash is if I log out and log in as multiple users on my app, That would also create multi FC user properties and i believe the SDK is trying to persist that info. Otherwise it is totally random.

I do have some crash logs for crashes related to coredata on freshchat happening on my production app.


Here is the stack trace of the thread that crashed for your reference:

Fatal Exception: NSInvalidArgumentException
+entityForName: nil is not a legal NSPersistentStoreCoordinator for searching for entity name 'FCUserProperties'

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x20883527c __exceptionPreprocess
1  libobjc.A.dylib                0x207a0f9f8 objc_exception_throw
2  CoreData                       0x20b315ff0 -[NSAttributeDescription defaultValue]
3  CoreData                       0x20b2cbec0 -[NSFetchRequest(_NSInternalMethods) _resolveEntityWithContext:]
4  CoreData                       0x20b293b4c -[NSManagedObjectContext executeFetchRequest:error:]
5  Vantage Circle                 0x10138d3e0 +[FCUserProperties getCustomPropertyWithKey:andUserProperty:withContext:]
6  Vantage Circle                 0x10138d160 +[FCUserProperties createNewPropertyForKey:WithValue:isUserProperty:]
7  Vantage Circle                 0x101423b58 __31-[Freshchat setUserProperties:]_block_invoke
8  CoreData                       0x20b3c7b28 developerSubmittedBlockToNSManagedObjectContextPerform
9  libdispatch.dylib              0x2082757d4 _dispatch_client_callout
10 libdispatch.dylib              0x208223004 _dispatch_main_queue_callback_4CF$VARIANT$mp
11 CoreFoundation                 0x2087c6c1c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
12 CoreFoundation                 0x2087c1b54 __CFRunLoopRun
13 CoreFoundation                 0x2087c10b0 CFRunLoopRunSpecific
14 GraphicsServices               0x20a9c179c GSEventRunModal
15 UIKitCore                      0x234ff7978 UIApplicationMain
16 Vantage Circle                 0x100f77540 main + 15 (AppDelegate.swift:15)
17 libdyld.dylib                  0x2082868e0 start

**Comment by harish-kumarc** [comment]
Thanks for the logs @kinshukkashyap .. We will analyse and fix all these. Also do you and additional info about crashes like - SDK version, iOS Version, Device, crash state background or background.

**Comment by kinshukkashyap** [comment]
Sorry for the delayed replay @harish-kumarc , Here are the info you requested:

1. SDK Version - 2.5.2
2. iOS Version - Varies but is always a iOS 12 release
3. Device - Have seen it on a variety of devices from iPhone 6 to iPhone XS Max (100+ users affected)
4. Mostly foreground (1% background is shown by crashlytics)

Here are some screenshots attached for your reference as well

![Screenshot 2019-11-25 at 9 11 10 PM](https://user-images.githubusercontent.com/16076281/69554902-793ae480-0fc8-11ea-8df2-6a64a519a96a.png)
![Screenshot 2019-11-25 at 9 12 51 PM](https://user-images.githubusercontent.com/16076281/69554913-7d670200-0fc8-11ea-8090-117c7e0433fc.png)

**Comment by mBilal5674** [comment]
It's still happening.

**Comment by harish-kumarc** [comment]
@mBilal5674 , Thanks for the data. We have identified the issue and planning to push it out in next SDK release (~February first week).

**Comment by kinshukkashyap** [comment]
@harish-kumarc any update on this ?

**Comment by harish-kumarc** [comment]
Hi @kinshukkashyap we have made CoreData improvements with [v3.2.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.2.2) SDK. Can you please update and let us if the crash is fixed for you. Modal path warning will be fixed future release(s).

**Comment by kinshukkashyap** [comment]
@harish-kumarc Thanks for the update. Have updated the pod and have added to our next release build. Will keep you reported if i find any issues.

**Comment by harish-kumarc** [comment]
@kinshukkashyap we have fixed the console warning also https://github.com/freshdesk/freshchat-ios/issues/65#issue-516591739 with release [v3.3.3](https://github.com/freshdesk/freshchat-ios/issues/65#issue-516591739)
