### ISSUE TITLE
Freshchat crash

### ISSUE THREAD

**Issue by Lucodalack** [freshdesk/freshchat-ios#66]
I've seen several crashes occur in ios 13 and foreground, this is my crash log
`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x19004098c __exceptionPreprocess
1  libobjc.A.dylib                0x18fd690a4 objc_exception_throw
2  CoreFoundation                 0x1900963f8 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x19009f938 -[__NSDictionaryM setObject:forKey:].cold.3
4  CoreFoundation                 0x18ff1c1cc -[__NSDictionaryM setObject:forKey:]
5  FoodyNowPartners               0x10357e0a8 -[FCMessageController willMoveToParentViewController:]
6  UIKitCore                      0x193a45e28 -[UIViewController _addChildViewController:performHierarchyCheck:notifyWillMove:]
7  FoodyNowPartners               0x103555ddc -[FCContainerController viewDidLoad]
8  UIKitCore                      0x193a3d07c -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]
9  UIKitCore                      0x193a41b8c -[UIViewController loadViewIfRequired]
10 UIKitCore                      0x1939b3e68 -[UINavigationController _updateScrollViewFromViewController:toViewController:]
11 UIKitCore                      0x1939b4174 -[UINavigationController _startTransition:fromViewController:toViewController:]
12 UIKitCore                      0x1939b4fa8 -[UINavigationController _startDeferredTransitionIfNeeded:]
13 UIKitCore                      0x19399ef28 -[UINavigationController _setViewControllers_7_0:transition:animated:operation:]
14 UIKitCore                      0x19399e048 -[UINavigationController _setViewControllers:transition:animated:operation:]
15 UIKitCore                      0x19399d2a4 __54-[UINavigationController setViewControllers:animated:]_block_invoke
16 UIKitCore                      0x193a4eda0 +[UIViewController _performWithoutDeferringTransitionsAllowingAnimation:actions:]
17 UIKitCore                      0x19399cd00 -[UINavigationController setViewControllers:animated:]
18 FoodyNowPartners               0x10351dae8 -[FCInterstitialViewController resetNavigationStackWithController:]
19 FoodyNowPartners               0x10351d08c __61-[FCInterstitialViewController handleConversations:andEmbed:]_block_invoke
20 libdispatch.dylib              0x18fd0d610 _dispatch_call_block_and_release
21 libdispatch.dylib              0x18fd0e184 _dispatch_client_callout
22 libdispatch.dylib              0x18fcc01d0 _dispatch_main_queue_callback_4CF$VARIANT$mp
23 CoreFoundation                 0x18ffbe3c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
24 CoreFoundation                 0x18ffb93b8 __CFRunLoopRun
25 CoreFoundation                 0x18ffb88bc CFRunLoopRunSpecific
26 GraphicsServices               0x199e24328 GSEventRunModal
27 UIKitCore                      0x19404e6d4 UIApplicationMain
28 FoodyNowPartners               0x102fc19b8 main + 20 (PushManager.swift:20)
29 libdyld.dylib                  0x18fe43460 start`

**Comment by harish-kumarc** [comment]
Thanks @Lucodalack for the log, Can you please share the steps to reproduce the crash with device info and SDK version.

**Comment by Geoffrey-T** [comment]
If this screen can help you
<img width="794" alt="Screenshot 2019-11-14 at 11 09 22" src="https://user-images.githubusercontent.com/2649445/68847644-47c04000-06cf-11ea-98b5-b335eb2a5516.png">

**Comment by Lucodalack** [comment]
i see this issue in my crashlitics and actually i dont know how to reproduce it 
I'm using :
SDK: 2.8.1
ios ver: 13

**Comment by harish-kumarc** [comment]
Thanks again @Lucodalack for the information. We will analyse the logs and surely resolve this in our future release(s).

**Comment by failynsedik** [comment]
Same here. Experiencing a crash, but different crash log.

![Screen Shot 2020-04-02 at 11 05 54 AM](https://user-images.githubusercontent.com/52100901/78206674-12778b80-74d2-11ea-8f74-ffce6802f9fc.png)

**Comment by harish-kumarc** [comment]
@failynsedik , can you let us know which version of iOS SDK are you facing this crash.

**Comment by hb2708** [comment]
@harish-kumarc I also started getting crash i updated the sdk to **3.7.0** and it happened some times only first time chat user so far


```
Fatal Exception: NSInvalidArgumentException
*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: 7)
-[FCMessageController willMoveToParentViewController:]

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1b1e78794 __exceptionPreprocess
1  libobjc.A.dylib                0x1b1b9abcc objc_exception_throw
2  CoreFoundation                 0x1b1ece2dc -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1b1ed7920 -[__NSDictionaryM setObject:forKey:].cold.3
4  CoreFoundation                 0x1b1d54ff8 -[__NSDictionaryM setObject:forKey:]
5  Dah Makan Dev                  0x10448d5b4 -[FCMessageController willMoveToParentViewController:]
6  UIKitCore                      0x1b58e0444 -[UIViewController _addChildViewController:performHierarchyCheck:notifyWillMove:]
7  Dah Makan Dev                  0x1044561bc -[FCContainerController viewDidLoad]
8  UIKitCore                      0x1b58d7750 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]
9  UIKitCore                      0x1b58dc1e0 -[UIViewController loadViewIfRequired]
10 UIKitCore                      0x1b584ec10 -[UINavigationController _updateScrollViewFromViewController:toViewController:]
11 UIKitCore                      0x1b584ef30 -[UINavigationController _startTransition:fromViewController:toViewController:]
12 UIKitCore                      0x1b584fdd4 -[UINavigationController _startDeferredTransitionIfNeeded:]
13 UIKitCore                      0x1b58510c4 -[UINavigationController __viewWillLayoutSubviews]
14 UIKitCore                      0x1b5834624 -[UILayoutContainerView layoutSubviews]
15 UIKitCore                      0x1b63d385c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
16 QuartzCore                     0x1b8966724 -[CALayer layoutSublayers]
17 QuartzCore                     0x1b896c87c CA::Layer::layout_if_needed(CA::Transaction*)
18 QuartzCore                     0x1b89773c0 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
19 QuartzCore                     0x1b88bff1c CA::Context::commit_transaction(CA::Transaction*, double)
20 QuartzCore                     0x1b88e98bc CA::Transaction::commit()
21 QuartzCore                     0x1b88ea2d0 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
22 CoreFoundation                 0x1b1df606c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
23 CoreFoundation                 0x1b1df0f60 __CFRunLoopDoObservers
24 CoreFoundation                 0x1b1df13dc __CFRunLoopRun
25 CoreFoundation                 0x1b1df0ce8 CFRunLoopRunSpecific
26 GraphicsServices               0x1bbf3b38c GSEventRunModal
27 UIKitCore                      0x1b5f1f444 UIApplicationMain
28 Dah Makan Dev                  0x102fbfa2c main + 15 (main.m:15)
29 libdyld.dylib                  0x1b1c788f0 start
```

attaching long for reference

**Comment by hb2708** [comment]
my crash looks same yours @Geoffrey-T does that still happens for you?

**Comment by Geoffrey-T** [comment]
@hb2708 Crash still happen for me, but it's insubstantial considering number of occurrences.

**Comment by hb2708** [comment]
@Geoffrey-T What sdk version you have currently coz my one happed in the test build so far when I updated the sdk  so if the sdk update is the reason I might just discard the sdk update then

@harish-kumarc I updated from **2.5.2** to **3.7.0**

**Comment by Geoffrey-T** [comment]
@hb2708 Version in production is 3.2.1, and 3.7.0 will be live in few days... I keep you posted if crashes number increase after it.

**Comment by hb2708** [comment]
@harish-kumarc @SanjithKanagavel @hemanth-sudarsan Anyone of you did checked on this seems like it's been there since few releases. Not that frequent but it happens

**Comment by hemanth-sudarsan** [comment]
@hb2708 We have fixed this issue. Please check in the latest version, if problem persists please feel free to open this.
