### ISSUE TITLE
Swift: How to know when FAQ or CHAT it's closed?

### ISSUE THREAD

**Issue by DouglasHennrich** [freshdesk/freshchat-ios#68]
I search through events and there isn't a event to let me know when the user dismiss `Freshchat`

**Comment by harish-kumarc** [comment]
Hi @DouglasHennrich , We are not exposing any SDK events for closing Freshchat solutions screen. Can you please help us in understanding the use case to achieve with it.
Thanks

**Comment by DouglasHennrich** [comment]
I was creating a viewcontroller just to show up Freshchat. So I have to know when the Freshchat was dismiss so I can close this viewcontroller too

**Comment by harish-kumarc** [comment]
Hi Douglas, As mentioned there is no close event, So can you try archiving same via adding an active view check logic or with viewWillAppear method in FreshchatSDK presenting view controller. Let us know if you are able to make it.

**Comment by DouglasHennrich** [comment]
Didn't thought about it 🤔 Thanks
