### ISSUE TITLE
Crash in FAQ on iOS

### ISSUE THREAD

**Issue by savy-91** [freshdesk/freshchat-ios#69]
We are currently experiencing a crash in our app built using flutter on iOS only.

*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6fe94 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	5   flutter_freshchat                   0x0000000112cfd92d -[FDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] + 476
	6   flutter_freshchat                   0x0000000112d67466 -[FDWebImageDownloader URLSession:task:didCompleteWithError:] + 113
	7   CFNetwork                           0x00007fff22f2dcd0 _CFNetworkHTTPConnectionCacheSetL<…>

The crash happens on all versions of iOS, the stack above is from iOS 13.2 on iPhone 11.

Previously, we were using version 2.5.1 and it was already happening. Upgrading to version 2.9.0 did not fix the error.
Please find below the crashlytics report for version 2.5.1.
![image](https://user-images.githubusercontent.com/6215122/68935006-1790a400-0798-11ea-9415-63747b74ece5.png)

We noticed that the issue  did not happen when we only had a few FAQs without icons and it did happen after we added icons to the categories, however we are not able to remove the icons ad this is not allowed by your system.

**Comment by savy-91** [comment]
UPDATE: I managed to remove the icons from the categories and it still crashes in the same way

**Comment by harish-kumarc** [comment]
@savy-91 Officially we are not supporting Freshchat for Flutter. And sure how you have build and added the SDK while creating your own FreshchatSDK.
Can you please try adding "-all_load", "-objC" flags in Project Settings, General > Build Settings > Other Linker flags.
Let us know if this fixes the issue.

**Comment by harish-kumarc** [comment]
Closing the issue, let us know if you are still facing it.

**Comment by mohdkhmais** [comment]
@harish-kumarc  @savy-91 I have done everything you mentioned still getting the crash problem. is there any solution yet ?

**Comment by harish-kumarc** [comment]
@mohdkhmais can you please share a sample app as we aren't able to replicate above issue after adding checks mentioned in https://github.com/freshdesk/freshchat-ios/issues/69#issuecomment-557883541

**Comment by mohdkhmais** [comment]
@harish-kumarc I have added these flags as you said "adding "-all_load", "-objC" flags in Project Settings, General > Build Settings > Other Linker flags." still same thing

**Comment by harish-kumarc** [comment]
@mohdkhmais  Are you creating your own Freshchat Flutter SDK or using third party SDK?

**Comment by mohdkhmais** [comment]
@harish-kumarc No i am using the third party https://pub.dev/packages/flutter_freshchat , it crashes when i call the freshchat.init method

**Comment by harish-kumarc** [comment]
@mohdkhmais , As the repository isn't maintain by Freshchat, Can you please post your issue under repo https://github.com/fayeed/flutter_freshchat. Also please check closed/active issues there, this will surly help you in fixing the issue.

**Comment by rahuldange09** [comment]
Sorry to reopen this issue? but @mohdkhmais @savy-91  is anyone resolved this issue?
@harish-kumarc please consider adding official support to flutter. As its started getting used widely

**Comment by mohdkhmais** [comment]
@harish-kumarc i agree with @rahuldange09 , i found another crash with this plugin , it crashes at first time when you open your application i think it is in "freshchat.init" and the Second time is when you set auto message (when you are not in office time) it crashes whenever you open the chat screen.
