### ISSUE TITLE
Umbrella header does not match SDK naming conventions

### ISSUE THREAD

**Issue by hansemannn** [freshdesk/freshchat-ios#7]
Hey there! One of our customers wants to use your SDK for their iOS application. They use [Appcelerator Hyperloop](http://www.appcelerator.com/mobile-app-development-products/hyperloop/) to access the SDK through JavaScript, but are not able to use it due to the fact that the umbrella-header (Freshchat.h) is named differently to the framework name (FreshchatSDK). This is quite uncommon, so Hyperloop is not supposed to handle it manually.

I would like to propose a tiny change that could be realized in two possible ways:

1) Rename `Freshchat.h` to `FreshchatSDK.h` to enable proper naming conventions
2) Use a module-map to define the correct umbrella header for your framework. Example
```
framework module FreshchatSDK {
  umbrella header "Freshchat.h"
  export *
}
```

I would file a pull-request, but as this SDK unfortunately is closed source and the source likely depend on the naming of the umbrella-header, I'd rather see this done by the Freshdesk team. Let us know if you need more context here, thanks!

**Comment by harish-kumarc** [comment]
@hansemannn, Thanks for reporting this, we will improve this in a future release.

**Comment by harish-kumarc** [comment]
@hansemannn, In latest release v1.3.0 we have updated SDK header file from Freshchat.h to FreshchatSDK.h for naming consistency. Do let us know if the header conflict issue is fixed with newer version.

**Comment by hansemannn** [comment]
Awesome, appreciate it @harish-kumarc! :-)
