### ISSUE TITLE
Loading indefinitely Sometimes

### ISSUE THREAD

**Issue by biazmoreira** [freshdesk/freshchat-ios#71]
Hello,

I did a small investigation with the Android SDK and IOS SDK last week using a free account. I used this free account APP Key and APP Id. After that, the company I work for decided to proceed on using FreshChat. Then, I changed to use their APP Key and APP Id and after that I'm stuck on the loading messages screen. I can't test nor doing anything. Both iOS and Android are stuck on the loading screen. Can you please help?

**Comment by harish-kumarc** [comment]
Hi @biancamoreiragyg . Really sorry for the inconvenience. There are only three cases only where you see infinite loading into your app
1. Check if your AppId and AppKey are added in correct order.
2. If you are clearing keychain(For iOS) store after initialising in freshchatSDK.
3. If config domain value is missing. Check your Freshchat portal URL. if its NOT **web.freshchat.com**, then in config domain replace **web** with **msdk**
For example if your portal domain is - **web.eu.freshchat.com** then in sdk domain config value will be **msdk.eu.freshchat.com**

Please let us know if you are able to fix it. Also you can write to support@freshchat.com, where our support agents will help you in fixing the issue.

Thanks

**Comment by mikhailmelnik** [comment]
@harish-kumarc it will be great to have information about domain mentioned in documentation. I've spent half a day fighting infinite spinners on android and debugging app until guessed it might be related to domain (again, just because I was experimenting with web version and at some point it started displaying nothing until I've replaced the host) and finally getting to this issue.

**Comment by harish-kumarc** [comment]
Thanks @mikhailmelnik , Default domain for Freshchat is msdk.freshchat.com and for that customers don't need to update anything from SDK. But if a customer wants a region specific account then our account manger will define that, but in some cases from either of the sides its missed and that create the issue. We have noted it and surly improve this.

**Comment by mallikarjun046** [comment]
Loading indefinitely for the first time(android)

**Comment by nimi0112** [comment]
@mallikarjun046  how did you resolve this issue?
