### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by iamsanketray123** [freshdesk/freshchat-ios#75]
How do I make sure to display the conversation page in full screen in iOS 13?

**Comment by harish-kumarc** [comment]
Hi @iamsanketray123 , Apple introduced a new default card presentation from iOS and to get fullscreen you have to specify it explicitly as fullScreen with modelPresentationStyle. 
Like : -
```
let viewCtr = UIViewController()
viewCtr.modalPresentationStyle = .fullScreen
self.present(viewCtr, animated: true, completion: nil)
```

**Comment by iamsanketray123** [comment]
`Freshchat.sharedInstance().showConversations(self, with: options)`
How do I convert this to the above format?

**Comment by harish-kumarc** [comment]
Hi @iamsanketray123 , looks like you are using old version of SDK. Please use `pod update` to install latest version that has default fullscreen view for Freshchat screens.
