### ISSUE TITLE
'FreshchatInvalidArgumentException', reason: 'Initialization failed : FreshchatSDK initialized with invalid AppKey!'

### ISSUE THREAD

**Issue by muhammadashfaq** [freshdesk/freshchat-ios#76]
Hi i am integrating freshdesk in one of my app.

I am giving APP_ID and API_KEY from  My FreshDesk Pannel.

Can anybody tell what is diffrence between APP_KEY and API_KEy are they same or diffrent. if they are diffrent then from where i can get APP_KEY ?

**Comment by harish-kumarc** [comment]
Hi @muhammadashfaq , APP_ID and API_KEY are two separate keys in UUID format that defines unique account identity with Freshchat. You can get them in **Mobile SDK** section under **Settings** (last icon centre left) in **Freshchat** portal https://web.freshchat.com, same mentioned under **Get your APP ID and APP Key** in documentation guide [here](https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps).
