### ISSUE TITLE
Crashing issue when using search on iOS13

### ISSUE THREAD

**Issue by philgrida** [freshdesk/freshchat-ios#77]
When tapping the search button in the FAQ window when on a iOS13 device (iPhone), the app will crash and raises the following exception :

<Access to UISearchBar's _searchField ivar is prohibited. This is an application bug> <{
    "UncaughtExceptionHandlerAddressesKey_PIM" =     (
        "4   libc++abi.dylib                     0x0000000185043304 08F81BAA-B7B7-3E6C-B674-4227D40E6BFD + 58116",
        "5   libc++abi.dylib                     0x0000000185042ed8 __cxa_rethrow + 144",
        "6   libobjc.A.dylib                     0x0000000184f9e158 objc_exception_rethrow + 40",
        "7   CoreFoundation                      0x00000001851eeb4c CFRunLoopRunSpecific + 576",
        "8   GraphicsServices                    0x000000018f174328 GSEventRunModal + 104"
    );

Can this be fixed ?

The window is also not full screen. How can it be made full screen in objective-c?

It works fine on an iOS12 and below device.

Phil.

**Comment by harish-kumarc** [comment]
Hi @philgrida , Yes the crash happens when you are using old version od SDK(< 2.7.2) and build your project with Xcode 11.
We have fixed it with [ v2.7.2](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.7.2). Please update to latest SDK and do let us know if its resolved.
Thanks

**Comment by philgrida** [comment]
All good thanks.
