### ISSUE TITLE
Message could not be sent programmatically

### ISSUE THREAD

**Issue by losernobody** [freshdesk/freshchat-ios#78]
I am using Freshchat SDK in an iOS app.

Using the UI provided by the SDK, it is possible to send and receive messages. The sent messages can be viewed in the dashboard.

However, I am not able to send messages programmatically. Following is the code used-
```swift
let message = FreshchatMessage(message: "something", andTag: "Inbox")

Freshchat.sharedInstance()?.send(message)
```

The above message is not found when the UI is shown to view messages using following code-
```swift
Freshchat.sharedInstance()?.showConversations(self)
```

The message is also not found in the dashboard in the web interface.

Can anyone point out what is the issue with the above code?
Can anyone point out how to send messages programmatically?

**Comment by harish-kumarc** [comment]
Hi @losernobody , the snippet you shared is correct and should work for send message programatically to specific tagged channel. And if the tag isn't match with target channel then message will go to default channel. 
Can you please check again under conversations filter section if conversation is auto-assigned to agent or auto-resolved or assigned to bot (based on your settings).
<img width="401" alt="Screenshot 2020-01-16 at 10 55 10 PM" src="https://user-images.githubusercontent.com/16202319/72547778-47047f80-38b3-11ea-83dc-41cfe6285d21.png">

Please let us know if you are able to find the conversation or else will go for screen share session to resolve the issue.

**Comment by losernobody** [comment]
I am unable to find the message in the dashboard.

https://github.com/losernobody/freshchatissue contains code to reproduce the issue. Please perform following steps-
- clone the above repository
- run the app
- Tap on "Send message" to send message programmatically
- Tap on "Show conversations" to view the conversations.

- The message that was sent programmatically will not be present in the conversations UI.

Please check.

**Comment by harish-kumarc** [comment]
Hi @losernobody 
We have checked the available channel via charles proxy for the sample you shared and found that there is no "**Inbox**" tag available for any of your active channel. You can add a tag via selecting a channel then **Advance Setting** then add tag and finally publish.
Ideally if there is no matching tag available then we redirect messages to default channel but in some cases "Default Channel" marker for a channel is missing and message send fails. Same happening in your case also.
Please try adding correct tag and try again. If the issue still persists will move to a screen share session.
Thanks

**Comment by losernobody** [comment]
After adding the tag to channel, messages can be sent programmatically.

Thanks for the help.
