### ISSUE TITLE
Shared instance with user not send to server

### ISSUE THREAD

**Issue by herarya** [freshdesk/freshchat-ios#8]
@SanjithKanagavel hi, i set instance with user, not show user info on fresh chat dashboard

this my code

 `let fchatConfig = FreshchatConfig.init(appID: appId, andAppKey: appKey) //Enter your AppID and AppKey here
   Freshchat.sharedInstance().initWith(fchatConfig)
    
    // Create a user object
    let user = FreshchatUser.sharedInstance();
    // To set an identifiable first name for the user
    user?.firstName = firstName;
    // To set an identifiable last name for the user
    user?.lastName = lastName;
    //To set user's email id
    user?.email = email;
    //To set user's phone number
    user?.phoneCountryCode = countryCode;
    user?.phoneNumber = phone;
    
    // FINALLY, REMEMBER TO SEND THE USER INFORMATION SET TO FRESHCHAT SERVERS
    Freshchat.sharedInstance().setUser(user)`

**Comment by SanjithKanagavel** [comment]
Hey @herarya. I could understand your query. 
- You could only see **registered Freshchat user** on your [dashboard](https://web.freshchat.com/people).
- User gets **registered when initiates message** (first message) from any of your channels. You can use this code `Freshchat.sharedInstance().showConversations(self)`  to present channels and try sending the message from any channel. 
- Also, you should be able to see the user information in the right panel under  **IOS DEVICE PROPERTIES** of the conversation you initiated on the [web portal](https://web.freshchat.com).


Try them and let us know.

**Comment by herarya** [comment]
@SanjithKanagavel hhaha, sorry my english not good, i mean user information not show, in Conversations dashboard inbox, https://web.freshchat.com/inbox/0/0 , 

now still random name like "Squeaking Donut"

**Comment by tryprasannan** [comment]
@herarya Do you see this for multiple users ? Do you have any specific steps to reproduce this issue ? We verified this on our sample and wasn't able to reproduce this issue.

**Comment by herarya** [comment]
@tryprasannan thanks for replay, we follow from this https://support.freshchat.com/support/solutions/articles/229394-freshchat-ios-sdk-swift-integration-guide

and this my full code

`@objc(FreshChatSdk)
class FreshChatSdk: NSObject {
  
  @objc func setInitFreshchatSDK(_ appId:String,appKey:String){
    let fchatConfig = FreshchatConfig.init(appID: appId, andAppKey: appKey) //Enter your AppID and AppKey here
    Freshchat.sharedInstance().initWith(fchatConfig);
  }
  @objc func setInitFreshchatSDKWithUser(_ appId:String,appKey:String,firstName:String,lastName:String,email:String,phone:String,countryCode:String){
    
    let fchatConfig = FreshchatConfig.init(appID: appId, andAppKey: appKey) //Enter your AppID and AppKey here
    Freshchat.sharedInstance().initWith(fchatConfig)
    // Create a user object
    let user = FreshchatUser.sharedInstance();
    // To set an identifiable first name for the user
    user?.firstName = firstName;
    // To set an identifiable last name for the user
    user?.lastName = lastName;
    //To set user's email id
    user?.email = email;
    //To set user's phone number
    user?.phoneCountryCode = countryCode;
    user?.phoneNumber = phone;
    // FINALLY, REMEMBER TO SEND THE USER INFORMATION SET TO FRESHCHAT SERVERS
    Freshchat.sharedInstance().setUser(user)
  }
  @objc func showScreenFaq(){
    
    let rootViewController:UIViewController? = UIApplication.shared.delegate?.window??.rootViewController!
    if rootViewController != nil {
      DispatchQueue.main.async {
        Freshchat.sharedInstance().showFAQs(rootViewController)
      }
    }
    
  }
  
  @objc func showScreenChat(){
    
    let rootViewController:UIViewController? = UIApplication.shared.delegate?.window??.rootViewController!
    if rootViewController != nil {
      DispatchQueue.main.async {
         Freshchat.sharedInstance().showConversations(rootViewController)
      }
    }
  }

}`

**Comment by SanjithKanagavel** [comment]
@herarya. I am not sure where you're calling **setInitFreshchatSDKWithUser** function. Also please confirm that you're using latest version of SDK.

I have attached a sample project with similar implementation as above please try them and let us know how it works.

[ObjectiveCSample.zip](https://github.com/freshdesk/freshchat-ios/files/1694589/ObjectiveCSample.zip)

**Comment by herarya** [comment]
@SanjithKanagavel @tryprasannan thanks bro, i recheck my code and update latest sdk 💃

**Comment by rv7284** [comment]
@herarya  I'm facing the same issue. Can you tell me how you solved it?

**Comment by sandeepbol** [comment]
same here

**Comment by herarya** [comment]
> @herarya I'm facing the same issue. Can you tell me how you solved it?

i just update latest version the sdk

**Comment by ilkerc** [comment]
> Hey @herarya. I can understand your query.
> 
> * You could only see **registered Freshchat user** on your [dashboard](https://web.freshchat.com/people).
> * User gets **registered when initiates message** (first message) from any of your channels. You can use this code `Freshchat.sharedInstance().showConversations(self)`  to present channels and try sending the message from any channel.
> * Also, you should be able to see the user information in the right panel under  **IOS DEVICE PROPERTIES** of the conversation you initiated on the [web portal](https://web.freshchat.com).
> 
> Try them and let us know.

`User gets **registered when initiates message** (first message) from any of your channels.`: You have to fix this, seriously.

What is the point to have segments, an only a bunch of users who had a problem and wanted to contact?  What is the point to have campaigns, much of my users already churn when they see a problem. So shall I use campaigns only for trying re-engaging dormant users? You just kill the product, literally making it useless on mobile, blocking me to target certain segments. I rather just leave an email address in the bottom.

**Comment by MuthuFD** [comment]
@ilkerc Please contact us at support@freshchat.com. We will check what can be done in your case.

**Comment by kurkutenr** [comment]
Why do we need this - when user registers **registered when initiates message** from any of your channels.
Even after trying this i don't see user/email in "All Users"  on fresh chat dashboard

Seriously, you need to fix this.

**Comment by jaythummar85** [comment]
@herarya 

can you try this?
I have the same issue. I can fix it set domain because my account was not part of the US server.

If your Freshchat account is not part of Freshchat US servers, you must specify domain based on your server location. Please contact our support team to know your account's server location. 

Following is the server location to domain mapping details

US2 - "https://msdk.us2.freshchat.com"
EU - "https://msdk.eu.freshchat.com"
AU - "https://msdk.au.freshchat.com"
IN - "https://msdk.in.freshchat.com"
