### ISSUE TITLE
resetUserWithCompletion: calls completion more than once

### ISSUE THREAD

**Issue by marcknock** [freshdesk/freshchat-ios#80]
When calling:

```
-(void)resetUserWithCompletion:(void (^)())completion
```

The completion is called more than once. I don't know if this is expected behavior or not, but usually completion blocks are called once.

**Comment by harish-kumarc** [comment]
Hi @marcknock , Thanks for pointing out the issue, we are aware about it and surely release a new SDK version with fix by Feb.

**Comment by harish-kumarc** [comment]
@marcknock , The issue is fixed with [v3.3.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.3.0). Please update to latest SDK.

**Comment by marcknock** [comment]
Thank you for notifying me, as it was not included in the changelog.
