### ISSUE TITLE
Prefix push notifications alert body with support agent name

### ISSUE THREAD

**Issue by marcknock** [freshdesk/freshchat-ios#82]
On iOS, the push notifications received from Freschat should be prefixed with the Support Agent's name sending them.

Right now you just get the message body, which makes it hard to distinguish if this is a support message or not. Push notifications for an app may not be entirely used for Freshchat.

Better yet, allow us to configure this in the Freshchat admin panel.

**Comment by harish-kumarc** [comment]
hi @marcknock , we have an api `Freshchat.sharedInstance().isFreshchatNotification` that should be used in notification handling to distinguish if the notification is from Freshchat or from other source. Please check [section 6](https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps) under documentation guide. 
After clicking the push notification we are forwarding the user to correct message channel screen.

In message detail screen customer can hide/add placeholder for agent name and showing/sending agent name in such situations conflict with settings so we aren't sending Agent name with push payload.

**Comment by marcknock** [comment]
Thank you for the reply.

I am not asking about identifying Freshchat messages in the SDK. I am asking about the customer experience, what the users sees on their lock screen.

> In message detail screen customer can hide/add placeholder for agent name and showing/sending agent name in such situations conflict with settings so we aren't sending Agent name with push payload.

Where exactly is this on the Freschat admin page? Are you saying there is a setting which will prefix the message body in the APNS alert with the sender's name? As this is what we want.

**Comment by harish-kumarc** [comment]
Currently we aren't providing any option or settings to add or prefix agent name with message text reply in Freshchat push notifications.
Above refers to **Message detail screen in SDK** or chat screen and agent name can be configured there based on SDK init configs. By default Agent name is available for all agent messages. If they want a placeholder text or Company name instead then `config.teamMemberInfoVisible = false` will hide that and name can be set form localised sdk string file (keyname `messages_agent_label_text`, can be empty to completely hide agent name).
 
So we are not supporting prefix or adding agent name as this will create issues for existing customers who do not what to show or hide agent names.
