### ISSUE TITLE
In-app notification banner overlaps status bar

### ISSUE THREAD

**Issue by marcknock** [freshdesk/freshchat-ios#83]
I guess this really depends on iOS version and how the status bar is handled in the app.

In any case, let me know if I can provide you with more information. None of the content in the notification banner should be under the status bar's text.

Also, please consider that an app may have a dark or light status bar, you should adjust your background accordingly to that.

![IMG_0046](https://user-images.githubusercontent.com/43761071/73579154-87790700-4436-11ea-90f4-541dcde35550.PNG)

**Comment by harish-kumarc** [comment]
Hi @marcknock , For in app notification banner we are creating our custom view animated on top view so it is visible below status bar. We will fix inapp banner and status bar content overlapping in coming release(s).

**Comment by harish-kumarc** [comment]
Hi @marcknock , We have fixed the issue with latest release [v3.3.3](https://github.com/freshdesk/freshchat-ios/releases/tag/v3.3.3)
