### ISSUE TITLE
Callling Freshchat.sharedInstance().identifyUser does not set FreshchatUser.sharedInstance().restoreID or externalID

### ISSUE THREAD

**Issue by marcknock** [freshdesk/freshchat-ios#85]
Callling Freshchat.sharedInstance().identifyUser does not set FreshchatUser.sharedInstance().restoreID or externalID

If the identifyUser API is not immediate, there should be a completion block. Otherwise, FreshchatUser, which I assume from the API, is a singleton, should have both restoreID and externalID set to what was called in identifyUser

**Comment by harish-kumarc** [comment]
Hi @marcknock , User restore ID will be generated only when customer starts a message with Freshchat that may happen after many sessions of app usage. So we are trigger local notification for restoreId and that can be listened in application(also updated with FreshchatUser) and restoreId can be updated to database for future restore call.

**Comment by harish-kumarc** [comment]
https://github.com/freshdesk/freshchat-ios/issues/85#issuecomment-582431940
This clears why completion block isn't suitable for restoreId.
Closing the issue.
