### ISSUE TITLE
Annotate FreshchatSDK.h with nullability attributes

### ISSUE THREAD

**Issue by marcknock** [freshdesk/freshchat-ios#86]
This is essential for proper Swift integration, as well as for code clarity:

https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/designating_nullability_in_objective-c_apis

**Comment by hemanth-sudarsan** [comment]
@marcknock Will be doing it in future release and update you.

**Comment by hemanth-sudarsan** [comment]
@marcknock In our latest release we have made the changes. Please update to the latest version v3.3.3.
