### ISSUE TITLE
'FreshchatSDK/FreshchatSDK.h' file not found

### ISSUE THREAD

**Issue by tengfoung** [freshdesk/freshchat-ios#88]
Compilation error "'FreshchatSDK/FreshchatSDK.h' file not found" when trying to run testing on the SwiftSample project.

Xcode version: 11.2.1

![Screenshot 2020-02-07 at 6 51 49 PM](https://user-images.githubusercontent.com/4436592/74023678-2d9ab300-49db-11ea-9957-af512b944242.png)

You may find the Xcode 11 compatible project here: https://github.com/tengfoung/freshchat-ios/tree/swift-5

**Comment by hemanth-sudarsan** [comment]
Hi @tengfoung We ran your project in Xcode 11.3.1 and 11.3, it is working completely fine. We will check in Xcode 11.2.1 and confirm too.

**Comment by tengfoung** [comment]
@hemanth-sudarsan it will only reproducible when `cmd+u`

**Comment by hemanth-sudarsan** [comment]
@tengfoung 
Podfile Should be like this,
```
pod 'FreshchatSDK'

target 'SwiftSample' do
  use_frameworks!
end

target "SwiftSampleTests" do
end

target "SwiftSampleUITests" do
end
```
And this one works.

**Comment by hemanth-sudarsan** [comment]
@tengfoung Closing this. Hope its been solved.

**Comment by agrawalsurabhi89** [comment]
I'm facing similar issue. What is the proper solution if anyone can help. I' trying to upgrade manually, Not using pods in my project
