### ISSUE TITLE
Cancel button does not work (Photos)

### ISSUE THREAD

**Issue by wjsimard** [freshdesk/freshchat-ios#9]
When clicking on "Upload from gallery" or "Take picture" in a conversation, the right button cancel in navigation bar does nothing.

**Comment by SanjithKanagavel** [comment]
Hi @wjsimard, 
This looks working in our devices and simulator. Can you please share us your iOS and Xcode version? If you are testing in Simulator, can you test in real device ?

**Comment by wjsimard** [comment]
Hi! I finally found it was another library named BlocksKit that was interfering. I was able to remove it from my project, but maybe you could investigate if time allows it. I was able to reproduce my situation in your Sample Project in Objective C by adding: pod 'BlocksKit' in the podfile. Thank you.

**Comment by SanjithKanagavel** [comment]
Thanks for letting us know this. We will try to reproduce it at our end and improve our SDK behaviour in upcoming releases.
