### ISSUE TITLE
Is Freshchat.sharedInstance() guaranteed to succeed?

### ISSUE THREAD

**Issue by samwyndham** [freshdesk/freshchat-ios#91]
From swift `Freshchat.sharedInstance()` returns an implicitly unwrapped optional object as the SDK doesn't have nullability annotations.

Is it safe to assume that this will always succeed? Looking at the [integration guidelines](https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps) there are 27 instances where the object is implicitly unwrapped and one where it is not.

**Comment by hemanth-sudarsan** [comment]
@samwyndham It will succeed all time. We will update with a nonnull object in future release.

**Comment by samwyndham** [comment]
Thanks @hemanth-sudarsan for the fast reply!

**Comment by hemanth-sudarsan** [comment]
Hi @samwyndham, we updated the SDK with nonnull object. Please update to the latest SDK.
