### ISSUE TITLE
Wrongly reported app version

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/freshchat-ios#92]
Freshchat always report version 1.0 as the app version to CS agents, regardless of what the actual version is. We're using Freshchat with Carthage, so this is probably the cause.

I believe this is related to this https://github.com/freshdesk/freshchat-ios/issues/29, as this is also related to loading information from a different Bundle.

**Comment by harish-kumarc** [comment]
@iangmaia Thanks, It is a known issue with Carthage both application version and version-code comes as 1in Freshchat web portal. We will push the fix in next release(s).

**Comment by harish-kumarc** [comment]
@iangmaia  we have fixed the issues with latest changes https://github.com/freshdesk/freshchat-ios/tree/carthage
