### ISSUE TITLE
The attach icon isn't appearing but is functioning. 

### ISSUE THREAD

**Issue by thecoffeehog** [freshdesk/freshchat-ios#93]
![image](https://user-images.githubusercontent.com/8275355/74337528-729d5b80-4dc6-11ea-8bd3-f97b2b3e3e16.png)

**Comment by harish-kumarc** [comment]
@thecoffeehog , Which SDK version are you using into your application?

**Comment by naren7229** [comment]
2.9.0

**Comment by naren7229** [comment]
> @thecoffeehog , Which SDK version are you using into your application?

2.9.0

**Comment by thecoffeehog** [comment]
Yes @harish-kumarc as @naren7229  said we are using the 2.9.0 version.

**Comment by harish-kumarc** [comment]
@thecoffeehog @naren7229 as visible from your screenshot looks, the chat message bubble background, send message  images are missing. This points that the `FCResources.bundle` or If you are using custom resource bundle not included(Target settings) with your project. Please check and correctly including bundle will fix attach icon also.

**Comment by thecoffeehog** [comment]
Thanks, @harish-kumarc! We will try this and get back if are unable to solve. cc: @naren7229

**Comment by thecoffeehog** [comment]
Also, @harish-kumarc are there any plans for an official Flutter package for Freshchat?

We are currently using https://pub.dev/packages/flutter_freshchat and it's probably getting difficult for the package developer to maintain it.  

I am pretty sure many Freshchat customers will appreciate this and many new ones as well.

**Comment by harish-kumarc** [comment]
@thecoffeehog We are exploring this from our side along with better maintainablility with new releases. We will have an official one but as third party flutter SDK is already available so its not in priority from our-side.

**Comment by thecoffeehog** [comment]
Thanks for the reply @harish-kumarc but the third party plugin has a host of issues and the experience with it on iOS is very bad, so if an official plugin for Freshchat was there it will help big time.

You can even confirm this with your sales team, they must have got a lot of queries regarding this. 

Intercom, Zendesk and others have official plugins for Flutter.

**Comment by harish-kumarc** [comment]
Hi @thecoffeehog  Correct, some queries are there for Flutter but we redirect them to the third party SDK only. We will surly take your feedback forward to team and mark it as a Feature request :). Also if the issue is resolved please feel to close it.

**Comment by thecoffeehog** [comment]
Thanks for considering the feedback @harish-kumarc 
Will close the issue.
