### ISSUE TITLE
Integration Guide URL broken

### ISSUE THREAD

**Issue by ifndefgt** [freshdesk/freshchat-ios#94]
Integration Guide URL is broken. And it's a blocker problem for SDK integration

**Comment by harish-kumarc** [comment]
Hi @ifndefgt , please follow the url below for SDK integration doc https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps
Also can you please URL you are trying from. Thanks.

**Comment by ifndefgt** [comment]
Hi @harish-kumarc , thank you for quick response.

I have just followed the URL in Readme.md

https://github.com/freshdesk/freshchat-ios/blob/master/README.md

which is

https://support.freshchat.com/support/solutions/articles/232945-freshchat-ios-sdk-integration

Thanks

**Comment by harish-kumarc** [comment]
@ifndefgt , we have migrated to new integration doc sometime back but missed the URL in README.md file. Thanks for letting us know about it : ). The URL is now updated with correct integration guide, sorry for the inconvenience.

**Comment by ifndefgt** [comment]
Thanks for your quick support. I didn't even feel the inconvenience.
