### ISSUE TITLE
Core data crash 

### ISSUE THREAD

**Issue by Lucodalack** [freshdesk/freshchat-ios#96]
I received several crash relate on core data in the newest version 3.2.2
this is my crash log 
`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x194072a48 __exceptionPreprocess
1  libobjc.A.dylib                0x193d99fa4 objc_exception_throw
2  CoreData                       0x1989b537c -[NSAttributeDescription defaultValue]
3  CoreData                       0x19895a33c +[NSEntityDescription insertNewObjectForEntityForName:inManagedObjectContext:]
4  FoodyNowPartners               0x104935e0c +[FCConversations createConversationWithID:ForChannel:]
5  FoodyNowPartners               0x1048f5d70 +[FCMessageServices processMessageResponse:]
6  FoodyNowPartners               0x1048f581c __55+[FCMessageServices fetchMessagesForSrc:andCompletion:]_block_invoke_4
7  libdispatch.dylib              0x193d3e610 _dispatch_call_block_and_release
8  libdispatch.dylib              0x193d3f184 _dispatch_client_callout
9  libdispatch.dylib              0x193d2234c _dispatch_main_queue_callback_4CF$VARIANT$armv81
10 CoreFoundation                 0x193ff05e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
11 CoreFoundation                 0x193feb5d8 __CFRunLoopRun
12 CoreFoundation                 0x193feaadc CFRunLoopRunSpecific
13 GraphicsServices               0x19df8b328 GSEventRunModal
14 UIKitCore                      0x1980f863c UIApplicationMain
15 FoodyNowPartners               0x1042b3870 main + 20 (PushManager.swift:20)
16 libdyld.dylib                  0x193e74360 start`
this is a background thread.

**Comment by harish-kumarc** [comment]
Thanks @Lucodalack thanks for logs. If possible can you send us steps to reproduce.

**Comment by Lucodalack** [comment]
It recorded in crashlytic, i also cant reproduce it

**Comment by harish-kumarc** [comment]
Hi @Lucodalack , We have fixed the the issue with release v3.3.3(https://github.com/freshdesk/freshchat-ios/releases/tag/v3.3.3).
