### ISSUE TITLE
Allow us to add custom field or at least an Identifier to FreshChatUser 

### ISSUE THREAD

**Issue by TheMrugraj** [freshdesk/freshchat-ios#97]
Currently, I am using iOS FreshChatHybridSDK and Using FreshChatUser Class to set users. Now, the concern is along with email address, first name, last name, etc. There should be some way to attach a unique ID based on our own system so on the support side we can identify the user easily. Also, in some cases, we may need a few other data to be sent along with Query which is not possible currently. There is a Field `ExternalID` but, it is a ReadOnly field.

**Comment by harish-kumarc** [comment]
Hi @TheMrugraj , ExternalID can be set with identifyUser API only. Once a user starts a new conversation you will get a restoreId(Check [documentation](https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps) for more) and can be accessed via user info. As both external as restoreId are unique and combination identifies user conversations so we aren't allowing user to set values.
Note : Hybrid SDK is in beta version only and its not consuming the latest widget.

**Comment by harish-kumarc** [comment]
Closing the issue.
